[build]
  # 构建命令
  command = "npm run build"
  # 构建输出目录
  publish = "dist"

[build.environment]
  # Node.js版本
  NODE_VERSION = "18"

# 函数配置
[functions]
  # 函数目录
  directory = "netlify/functions"

# 重定向规则 - 用于SPA路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 环境变量（在Netlify控制台中设置）
# GOOGLE_API_KEY = "your-google-api-key"

# 头部设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API函数的CORS设置
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"