/**
 * 音标模块数据文件
 * 包含默认音标字典和字典管理功能
 */

// 默认音标字典（常用单词）
const defaultDict = {
    // 基础词汇
    "hello": { us: "həˈloʊ", uk: "həˈləʊ" },
    "world": { us: "wɜːrld", uk: "wɜːld" },
    "good": { us: "ɡʊd", uk: "ɡʊd" },
    "morning": { us: "ˈmɔːrnɪŋ", uk: "ˈmɔːnɪŋ" },
    "afternoon": { us: "ˌæftərˈnuːn", uk: "ˌɑːftəˈnuːn" },
    "evening": { us: "ˈiːvnɪŋ", uk: "ˈiːvnɪŋ" },
    "night": { us: "naɪt", uk: "naɪt" },
    "thank": { us: "θæŋk", uk: "θæŋk" },
    "you": { us: "juː", uk: "juː" },
    "please": { us: "pliːz", uk: "pliːz" },
    "sorry": { us: "ˈsɔːri", uk: "ˈsɒri" },
    "excuse": { us: "ɪkˈskjuːs", uk: "ɪkˈskjuːs" },
    "me": { us: "miː", uk: "miː" },
    "yes": { us: "jes", uk: "jes" },
    "no": { us: "noʊ", uk: "nəʊ" },
    
    // 数字
    "one": { us: "wʌn", uk: "wʌn" },
    "two": { us: "tuː", uk: "tuː" },
    "three": { us: "θriː", uk: "θriː" },
    "four": { us: "fɔːr", uk: "fɔː" },
    "five": { us: "faɪv", uk: "faɪv" },
    "six": { us: "sɪks", uk: "sɪks" },
    "seven": { us: "ˈsevən", uk: "ˈsevən" },
    "eight": { us: "eɪt", uk: "eɪt" },
    "nine": { us: "naɪn", uk: "naɪn" },
    "ten": { us: "ten", uk: "ten" },
    
    // 颜色
    "red": { us: "red", uk: "red" },
    "blue": { us: "bluː", uk: "bluː" },
    "green": { us: "ɡriːn", uk: "ɡriːn" },
    "yellow": { us: "ˈjeloʊ", uk: "ˈjeləʊ" },
    "black": { us: "blæk", uk: "blæk" },
    "white": { us: "waɪt", uk: "waɪt" },
    "orange": { us: "ˈɔːrɪndʒ", uk: "ˈɒrɪndʒ" },
    "purple": { us: "ˈpɜːrpəl", uk: "ˈpɜːpəl" },
    "pink": { us: "pɪŋk", uk: "pɪŋk" },
    "brown": { us: "braʊn", uk: "braʊn" },
    
    // 家庭
    "family": { us: "ˈfæməli", uk: "ˈfæməli" },
    "father": { us: "ˈfɑːðər", uk: "ˈfɑːðə" },
    "mother": { us: "ˈmʌðər", uk: "ˈmʌðə" },
    "brother": { us: "ˈbrʌðər", uk: "ˈbrʌðə" },
    "sister": { us: "ˈsɪstər", uk: "ˈsɪstə" },
    "son": { us: "sʌn", uk: "sʌn" },
    "daughter": { us: "ˈdɔːtər", uk: "ˈdɔːtə" },
    "husband": { us: "ˈhʌzbənd", uk: "ˈhʌzbənd" },
    "wife": { us: "waɪf", uk: "waɪf" },
    "child": { us: "tʃaɪld", uk: "tʃaɪld" },
    "children": { us: "ˈtʃɪldrən", uk: "ˈtʃɪldrən" },
    
    // 时间
    "time": { us: "taɪm", uk: "taɪm" },
    "today": { us: "təˈdeɪ", uk: "təˈdeɪ" },
    "tomorrow": { us: "təˈmɔːroʊ", uk: "təˈmɒrəʊ" },
    "yesterday": { us: "ˈjestərdeɪ", uk: "ˈjestədeɪ" },
    "week": { us: "wiːk", uk: "wiːk" },
    "month": { us: "mʌnθ", uk: "mʌnθ" },
    "year": { us: "jɪr", uk: "jɪə" },
    "hour": { us: "ˈaʊər", uk: "ˈaʊə" },
    "minute": { us: "ˈmɪnɪt", uk: "ˈmɪnɪt" },
    "second": { us: "ˈsekənd", uk: "ˈsekənd" },
    
    // 食物
    "food": { us: "fuːd", uk: "fuːd" },
    "water": { us: "ˈwɔːtər", uk: "ˈwɔːtə" },
    "coffee": { us: "ˈkɔːfi", uk: "ˈkɒfi" },
    "tea": { us: "tiː", uk: "tiː" },
    "milk": { us: "mɪlk", uk: "mɪlk" },
    "bread": { us: "bred", uk: "bred" },
    "rice": { us: "raɪs", uk: "raɪs" },
    "meat": { us: "miːt", uk: "miːt" },
    "fish": { us: "fɪʃ", uk: "fɪʃ" },
    "fruit": { us: "fruːt", uk: "fruːt" },
    "apple": { us: "ˈæpəl", uk: "ˈæpəl" },
    "banana": { us: "bəˈnænə", uk: "bəˈnɑːnə" },
    
    // 动作
    "go": { us: "ɡoʊ", uk: "ɡəʊ" },
    "come": { us: "kʌm", uk: "kʌm" },
    "see": { us: "siː", uk: "siː" },
    "look": { us: "lʊk", uk: "lʊk" },
    "listen": { us: "ˈlɪsən", uk: "ˈlɪsən" },
    "speak": { us: "spiːk", uk: "spiːk" },
    "talk": { us: "tɔːk", uk: "tɔːk" },
    "read": { us: "riːd", uk: "riːd" },
    "write": { us: "raɪt", uk: "raɪt" },
    "eat": { us: "iːt", uk: "iːt" },
    "drink": { us: "drɪŋk", uk: "drɪŋk" },
    "sleep": { us: "sliːp", uk: "sliːp" },
    "work": { us: "wɜːrk", uk: "wɜːk" },
    "play": { us: "pleɪ", uk: "pleɪ" },
    "study": { us: "ˈstʌdi", uk: "ˈstʌdi" },
    "learn": { us: "lɜːrn", uk: "lɜːn" },
    "teach": { us: "tiːtʃ", uk: "tiːtʃ" },
    "help": { us: "help", uk: "help" },
    "give": { us: "ɡɪv", uk: "ɡɪv" },
    "take": { us: "teɪk", uk: "teɪk" },
    "buy": { us: "baɪ", uk: "baɪ" },
    "sell": { us: "sel", uk: "sel" },
    "make": { us: "meɪk", uk: "meɪk" },
    "do": { us: "duː", uk: "duː" },
    "have": { us: "hæv", uk: "hæv" },
    "be": { us: "biː", uk: "biː" },
    "get": { us: "ɡet", uk: "ɡet" },
    "put": { us: "pʊt", uk: "pʊt" },
    "find": { us: "faɪnd", uk: "faɪnd" },
    "know": { us: "noʊ", uk: "nəʊ" },
    "think": { us: "θɪŋk", uk: "θɪŋk" },
    "feel": { us: "fiːl", uk: "fiːl" },
    "want": { us: "wɑːnt", uk: "wɒnt" },
    "need": { us: "niːd", uk: "niːd" },
    "like": { us: "laɪk", uk: "laɪk" },
    "love": { us: "lʌv", uk: "lʌv" },
    "hate": { us: "heɪt", uk: "heɪt" },
    "hope": { us: "hoʊp", uk: "həʊp" },
    "try": { us: "traɪ", uk: "traɪ" },
    "use": { us: "juːz", uk: "juːz" },
    "open": { us: "ˈoʊpən", uk: "ˈəʊpən" },
    "close": { us: "kloʊz", uk: "kləʊz" },
    "start": { us: "stɑːrt", uk: "stɑːt" },
    "stop": { us: "stɑːp", uk: "stɒp" },
    "finish": { us: "ˈfɪnɪʃ", uk: "ˈfɪnɪʃ" },
    "begin": { us: "bɪˈɡɪn", uk: "bɪˈɡɪn" },
    "end": { us: "end", uk: "end" },
    "continue": { us: "kənˈtɪnjuː", uk: "kənˈtɪnjuː" },
    "wait": { us: "weɪt", uk: "weɪt" },
    "stay": { us: "steɪ", uk: "steɪ" },
    "leave": { us: "liːv", uk: "liːv" },
    "arrive": { us: "əˈraɪv", uk: "əˈraɪv" },
    "return": { us: "rɪˈtɜːrn", uk: "rɪˈtɜːn" },
    "turn": { us: "tɜːrn", uk: "tɜːn" },
    "walk": { us: "wɔːk", uk: "wɔːk" },
    "run": { us: "rʌn", uk: "rʌn" },
    "sit": { us: "sɪt", uk: "sɪt" },
    "stand": { us: "stænd", uk: "stænd" },
    "lie": { us: "laɪ", uk: "laɪ" },
    "fall": { us: "fɔːl", uk: "fɔːl" },
    "jump": { us: "dʒʌmp", uk: "dʒʌmp" },
    "fly": { us: "flaɪ", uk: "flaɪ" },
    "drive": { us: "draɪv", uk: "draɪv" },
    "ride": { us: "raɪd", uk: "raɪd" },
    "swim": { us: "swɪm", uk: "swɪm" },
    "dance": { us: "dæns", uk: "dɑːns" },
    "sing": { us: "sɪŋ", uk: "sɪŋ" },
    "laugh": { us: "læf", uk: "lɑːf" },
    "cry": { us: "kraɪ", uk: "kraɪ" },
    "smile": { us: "smaɪl", uk: "smaɪl" },
    "call": { us: "kɔːl", uk: "kɔːl" },
    "answer": { us: "ˈænsər", uk: "ˈɑːnsə" },
    "ask": { us: "æsk", uk: "ɑːsk" },
    "tell": { us: "tel", uk: "tel" },
    "say": { us: "seɪ", uk: "seɪ" },
    "show": { us: "ʃoʊ", uk: "ʃəʊ" },
    "hide": { us: "haɪd", uk: "haɪd" },
    "send": { us: "send", uk: "send" },
    "receive": { us: "rɪˈsiːv", uk: "rɪˈsiːv" },
    "bring": { us: "brɪŋ", uk: "brɪŋ" },
    "carry": { us: "ˈkæri", uk: "ˈkæri" },
    "hold": { us: "hoʊld", uk: "həʊld" },
    "catch": { us: "kætʃ", uk: "kætʃ" },
    "throw": { us: "θroʊ", uk: "θrəʊ" },
    "push": { us: "pʊʃ", uk: "pʊʃ" },
    "pull": { us: "pʊl", uk: "pʊl" },
    "lift": { us: "lɪft", uk: "lɪft" },
    "drop": { us: "drɑːp", uk: "drɒp" },
    "break": { us: "breɪk", uk: "breɪk" },
    "fix": { us: "fɪks", uk: "fɪks" },
    "build": { us: "bɪld", uk: "bɪld" },
    "create": { us: "kriˈeɪt", uk: "kriˈeɪt" },
    "destroy": { us: "dɪˈstrɔɪ", uk: "dɪˈstrɔɪ" },
    "clean": { us: "kliːn", uk: "kliːn" },
    "wash": { us: "wɑːʃ", uk: "wɒʃ" },
    "cook": { us: "kʊk", uk: "kʊk" },
    "cut": { us: "kʌt", uk: "kʌt" },
    "touch": { us: "tʌtʃ", uk: "tʌtʃ" },
    "hit": { us: "hɪt", uk: "hɪt" },
    "kick": { us: "kɪk", uk: "kɪk" },
    "kiss": { us: "kɪs", uk: "kɪs" },
    "hug": { us: "hʌɡ", uk: "hʌɡ" },
    "shake": { us: "ʃeɪk", uk: "ʃeɪk" },
    "wave": { us: "weɪv", uk: "weɪv" },
    "point": { us: "pɔɪnt", uk: "pɔɪnt" },
    "count": { us: "kaʊnt", uk: "kaʊnt" },
    "measure": { us: "ˈmeʒər", uk: "ˈmeʒə" },
    "weigh": { us: "weɪ", uk: "weɪ" },
    "compare": { us: "kəmˈper", uk: "kəmˈpeə" },
    "choose": { us: "tʃuːz", uk: "tʃuːz" },
    "decide": { us: "dɪˈsaɪd", uk: "dɪˈsaɪd" },
    "agree": { us: "əˈɡriː", uk: "əˈɡriː" },
    "disagree": { us: "ˌdɪsəˈɡriː", uk: "ˌdɪsəˈɡriː" },
    "believe": { us: "bɪˈliːv", uk: "bɪˈliːv" },
    "doubt": { us: "daʊt", uk: "daʊt" },
    "remember": { us: "rɪˈmembər", uk: "rɪˈmembə" },
    "forget": { us: "fərˈɡet", uk: "fəˈɡet" },
    "understand": { us: "ˌʌndərˈstænd", uk: "ˌʌndəˈstænd" },
    "explain": { us: "ɪkˈspleɪn", uk: "ɪkˈspleɪn" },
    "describe": { us: "dɪˈskraɪb", uk: "dɪˈskraɪb" },
    "mean": { us: "miːn", uk: "miːn" },
    "matter": { us: "ˈmætər", uk: "ˈmætə" },
    "happen": { us: "ˈhæpən", uk: "ˈhæpən" },
    "change": { us: "tʃeɪndʒ", uk: "tʃeɪndʒ" },
    "grow": { us: "ɡroʊ", uk: "ɡrəʊ" },
    "become": { us: "bɪˈkʌm", uk: "bɪˈkʌm" },
    "seem": { us: "siːm", uk: "siːm" },
    "appear": { us: "əˈpɪr", uk: "əˈpɪə" },
    "disappear": { us: "ˌdɪsəˈpɪr", uk: "ˌdɪsəˈpɪə" },
    "exist": { us: "ɪɡˈzɪst", uk: "ɪɡˈzɪst" },
    "live": { us: "lɪv", uk: "lɪv" },
    "die": { us: "daɪ", uk: "daɪ" },
    "born": { us: "bɔːrn", uk: "bɔːn" },
    "marry": { us: "ˈmæri", uk: "ˈmæri" },
    "divorce": { us: "dɪˈvɔːrs", uk: "dɪˈvɔːs" },
    "meet": { us: "miːt", uk: "miːt" },
    "visit": { us: "ˈvɪzɪt", uk: "ˈvɪzɪt" },
    "invite": { us: "ɪnˈvaɪt", uk: "ɪnˈvaɪt" },
    "welcome": { us: "ˈwelkəm", uk: "ˈwelkəm" },
    "join": { us: "dʒɔɪn", uk: "dʒɔɪn" },
    "follow": { us: "ˈfɑːloʊ", uk: "ˈfɒləʊ" },
    "lead": { us: "liːd", uk: "liːd" },
    "guide": { us: "ɡaɪd", uk: "ɡaɪd" },
    "protect": { us: "prəˈtekt", uk: "prəˈtekt" },
    "save": { us: "seɪv", uk: "seɪv" },
    "lose": { us: "luːz", uk: "luːz" },
    "win": { us: "wɪn", uk: "wɪn" },
    "fail": { us: "feɪl", uk: "feɪl" },
    "succeed": { us: "səkˈsiːd", uk: "səkˈsiːd" },
    "pass": { us: "pæs", uk: "pɑːs" },
    "miss": { us: "mɪs", uk: "mɪs" },
    "reach": { us: "riːtʃ", uk: "riːtʃ" },
    "achieve": { us: "əˈtʃiːv", uk: "əˈtʃiːv" },
    "complete": { us: "kəmˈpliːt", uk: "kəmˈpliːt" },
    "improve": { us: "ɪmˈpruːv", uk: "ɪmˈpruːv" },
    "develop": { us: "dɪˈveləp", uk: "dɪˈveləp" },
    "increase": { us: "ɪnˈkriːs", uk: "ɪnˈkriːs" },
    "decrease": { us: "dɪˈkriːs", uk: "dɪˈkriːs" },
    "reduce": { us: "rɪˈduːs", uk: "rɪˈdjuːs" },
    "add": { us: "æd", uk: "æd" },
    "remove": { us: "rɪˈmuːv", uk: "rɪˈmuːv" },
    "include": { us: "ɪnˈkluːd", uk: "ɪnˈkluːd" },
    "exclude": { us: "ɪkˈskluːd", uk: "ɪkˈskluːd" },
    "contain": { us: "kənˈteɪn", uk: "kənˈteɪn" },
    "fill": { us: "fɪl", uk: "fɪl" },
    "empty": { us: "ˈempti", uk: "ˈempti" },
    "full": { us: "fʊl", uk: "fʊl" },
    "share": { us: "ʃer", uk: "ʃeə" },
    "divide": { us: "dɪˈvaɪd", uk: "dɪˈvaɪd" },
    "separate": { us: "ˈsepəreɪt", uk: "ˈsepəreɪt" },
    "connect": { us: "kəˈnekt", uk: "kəˈnekt" },
    "join": { us: "dʒɔɪn", uk: "dʒɔɪn" },
    "combine": { us: "kəmˈbaɪn", uk: "kəmˈbaɪn" },
    "mix": { us: "mɪks", uk: "mɪks" },
    "match": { us: "mætʃ", uk: "mætʃ" },
    "fit": { us: "fɪt", uk: "fɪt" },
    "suit": { us: "suːt", uk: "suːt" },
    "wear": { us: "wer", uk: "weə" },
    "dress": { us: "dres", uk: "dres" },
    "undress": { us: "ʌnˈdres", uk: "ʌnˈdres" },
    "cover": { us: "ˈkʌvər", uk: "ˈkʌvə" },
    "uncover": { us: "ʌnˈkʌvər", uk: "ʌnˈkʌvə" },
    "wrap": { us: "ræp", uk: "ræp" },
    "unwrap": { us: "ʌnˈræp", uk: "ʌnˈræp" },
    "pack": { us: "pæk", uk: "pæk" },
    "unpack": { us: "ʌnˈpæk", uk: "ʌnˈpæk" },
    "load": { us: "loʊd", uk: "ləʊd" },
    "unload": { us: "ʌnˈloʊd", uk: "ʌnˈləʊd" },
    "lock": { us: "lɑːk", uk: "lɒk" },
    "unlock": { us: "ʌnˈlɑːk", uk: "ʌnˈlɒk" },
    "tie": { us: "taɪ", uk: "taɪ" },
    "untie": { us: "ʌnˈtaɪ", uk: "ʌnˈtaɪ" },
    "attach": { us: "əˈtætʃ", uk: "əˈtætʃ" },
    "detach": { us: "dɪˈtætʃ", uk: "dɪˈtætʃ" },
    "stick": { us: "stɪk", uk: "stɪk" },
    "unstick": { us: "ʌnˈstɪk", uk: "ʌnˈstɪk" },
    "glue": { us: "ɡluː", uk: "ɡluː" },
    "paste": { us: "peɪst", uk: "peɪst" },
    "tape": { us: "teɪp", uk: "teɪp" },
    "nail": { us: "neɪl", uk: "neɪl" },
    "screw": { us: "skruː", uk: "skruː" },
    "hammer": { us: "ˈhæmər", uk: "ˈhæmə" },
    "drill": { us: "drɪl", uk: "drɪl" },
    "saw": { us: "sɔː", uk: "sɔː" },
    "paint": { us: "peɪnt", uk: "peɪnt" },
    "draw": { us: "drɔː", uk: "drɔː" },
    "design": { us: "dɪˈzaɪn", uk: "dɪˈzaɪn" },
    "plan": { us: "plæn", uk: "plæn" },
    "prepare": { us: "prɪˈper", uk: "prɪˈpeə" },
    "organize": { us: "ˈɔːrɡənaɪz", uk: "ˈɔːɡənaɪz" },
    "arrange": { us: "əˈreɪndʒ", uk: "əˈreɪndʒ" },
    "order": { us: "ˈɔːrdər", uk: "ˈɔːdə" },
    "sort": { us: "sɔːrt", uk: "sɔːt" },
    "collect": { us: "kəˈlekt", uk: "kəˈlekt" },
    "gather": { us: "ˈɡæðər", uk: "ˈɡæðə" },
    "pick": { us: "pɪk", uk: "pɪk" },
    "select": { us: "sɪˈlekt", uk: "sɪˈlekt" },
    "search": { us: "sɜːrtʃ", uk: "sɜːtʃ" },
    "discover": { us: "dɪˈskʌvər", uk: "dɪˈskʌvə" },
    "explore": { us: "ɪkˈsplɔːr", uk: "ɪkˈsplɔː" },
    "investigate": { us: "ɪnˈvestɪɡeɪt", uk: "ɪnˈvestɪɡeɪt" },
    "examine": { us: "ɪɡˈzæmɪn", uk: "ɪɡˈzæmɪn" },
    "check": { us: "tʃek", uk: "tʃek" },
    "test": { us: "test", uk: "test" },
    "try": { us: "traɪ", uk: "traɪ" },
    "attempt": { us: "əˈtempt", uk: "əˈtempt" },
    "practice": { us: "ˈpræktɪs", uk: "ˈpræktɪs" },
    "exercise": { us: "ˈeksərsaɪz", uk: "ˈeksəsaɪz" },
    "train": { us: "treɪn", uk: "treɪn" },
    "educate": { us: "ˈedʒukeɪt", uk: "ˈedjukeɪt" },
    "inform": { us: "ɪnˈfɔːrm", uk: "ɪnˈfɔːm" },
    "warn": { us: "wɔːrn", uk: "wɔːn" },
    "advise": { us: "ədˈvaɪz", uk: "ədˈvaɪz" },
    "suggest": { us: "səˈdʒest", uk: "səˈdʒest" },
    "recommend": { us: "ˌrekəˈmend", uk: "ˌrekəˈmend" },
    "propose": { us: "prəˈpoʊz", uk: "prəˈpəʊz" },
    "offer": { us: "ˈɔːfər", uk: "ˈɒfə" },
    "provide": { us: "prəˈvaɪd", uk: "prəˈvaɪd" },
    "supply": { us: "səˈplaɪ", uk: "səˈplaɪ" },
    "deliver": { us: "dɪˈlɪvər", uk: "dɪˈlɪvə" },
    "serve": { us: "sɜːrv", uk: "sɜːv" },
    "support": { us: "səˈpɔːrt", uk: "səˈpɔːt" },
    "assist": { us: "əˈsɪst", uk: "əˈsɪst" },
    "aid": { us: "eɪd", uk: "eɪd" },
    "rescue": { us: "ˈreskjuː", uk: "ˈreskjuː" },
    "escape": { us: "ɪˈskeɪp", uk: "ɪˈskeɪp" },
    "avoid": { us: "əˈvɔɪd", uk: "əˈvɔɪd" },
    "prevent": { us: "prɪˈvent", uk: "prɪˈvent" },
    "allow": { us: "əˈlaʊ", uk: "əˈlaʊ" },
    "permit": { us: "pərˈmɪt", uk: "pəˈmɪt" },
    "forbid": { us: "fərˈbɪd", uk: "fəˈbɪd" },
    "ban": { us: "bæn", uk: "bæn" },
    "refuse": { us: "rɪˈfjuːz", uk: "rɪˈfjuːz" },
    "reject": { us: "rɪˈdʒekt", uk: "rɪˈdʒekt" },
    "accept": { us: "ækˈsept", uk: "ækˈsept" },
    "approve": { us: "əˈpruːv", uk: "əˈpruːv" },
    "confirm": { us: "kənˈfɜːrm", uk: "kənˈfɜːm" },
    "deny": { us: "dɪˈnaɪ", uk: "dɪˈnaɪ" },
    "admit": { us: "ədˈmɪt", uk: "ədˈmɪt" },
    "confess": { us: "kənˈfes", uk: "kənˈfes" },
    "declare": { us: "dɪˈkler", uk: "dɪˈkleə" },
    "announce": { us: "əˈnaʊns", uk: "əˈnaʊns" },
    "claim": { us: "kleɪm", uk: "kleɪm" },
    "argue": { us: "ˈɑːrɡjuː", uk: "ˈɑːɡjuː" },
    "discuss": { us: "dɪˈskʌs", uk: "dɪˈskʌs" },
    "debate": { us: "dɪˈbeɪt", uk: "dɪˈbeɪt" },
    "negotiate": { us: "nɪˈɡoʊʃieɪt", uk: "nɪˈɡəʊʃieɪt" },
    "bargain": { us: "ˈbɑːrɡən", uk: "ˈbɑːɡən" },
    "deal": { us: "diːl", uk: "diːl" },
    "trade": { us: "treɪd", uk: "treɪd" },
    "exchange": { us: "ɪksˈtʃeɪndʒ", uk: "ɪksˈtʃeɪndʒ" },
    "replace": { us: "rɪˈpleɪs", uk: "rɪˈpleɪs" },
    "substitute": { us: "ˈsʌbstɪtuːt", uk: "ˈsʌbstɪtjuːt" },
    "switch": { us: "swɪtʃ", uk: "swɪtʃ" },
    "transfer": { us: "trænsˈfɜːr", uk: "trænsˈfɜː" },
    "move": { us: "muːv", uk: "muːv" },
    "shift": { us: "ʃɪft", uk: "ʃɪft" },
    "slide": { us: "slaɪd", uk: "slaɪd" },
    "roll": { us: "roʊl", uk: "rəʊl" },
    "spin": { us: "spɪn", uk: "spɪn" },
    "rotate": { us: "ˈroʊteɪt", uk: "rəʊˈteɪt" },
    "twist": { us: "twɪst", uk: "twɪst" },
    "bend": { us: "bend", uk: "bend" },
    "fold": { us: "foʊld", uk: "fəʊld" },
    "unfold": { us: "ʌnˈfoʊld", uk: "ʌnˈfəʊld" },
    "stretch": { us: "stretʃ", uk: "stretʃ" },
    "squeeze": { us: "skwiːz", uk: "skwiːz" },
    "press": { us: "pres", uk: "pres" },
    "release": { us: "rɪˈliːs", uk: "rɪˈliːs" },
    "free": { us: "friː", uk: "friː" },
    "capture": { us: "ˈkæptʃər", uk: "ˈkæptʃə" },
    "trap": { us: "træp", uk: "træp" },
    "hunt": { us: "hʌnt", uk: "hʌnt" },
    "chase": { us: "tʃeɪs", uk: "tʃeɪs" },
    "pursue": { us: "pərˈsuː", uk: "pəˈsjuː" },
    "track": { us: "træk", uk: "træk" },
    "trace": { us: "treɪs", uk: "treɪs" },
    "follow": { us: "ˈfɑːloʊ", uk: "ˈfɒləʊ" },
    "accompany": { us: "əˈkʌmpəni", uk: "əˈkʌmpəni" },
    "escort": { us: "ɪˈskɔːrt", uk: "ɪˈskɔːt" },
    "attend": { us: "əˈtend", uk: "əˈtend" },
    "participate": { us: "pɑːrˈtɪsɪpeɪt", uk: "pɑːˈtɪsɪpeɪt" },
    "compete": { us: "kəmˈpiːt", uk: "kəmˈpiːt" },
    "race": { us: "reɪs", uk: "reɪs" },
    "fight": { us: "faɪt", uk: "faɪt" },
    "battle": { us: "ˈbætəl", uk: "ˈbætəl" },
    "war": { us: "wɔːr", uk: "wɔː" },
    "peace": { us: "piːs", uk: "piːs" },
    "calm": { us: "kɑːm", uk: "kɑːm" },
    "quiet": { us: "ˈkwaɪət", uk: "ˈkwaɪət" },
    "silent": { us: "ˈsaɪlənt", uk: "ˈsaɪlənt" },
    "loud": { us: "laʊd", uk: "laʊd" },
    "noisy": { us: "ˈnɔɪzi", uk: "ˈnɔɪzi" },
    "sound": { us: "saʊnd", uk: "saʊnd" },
    "hear": { us: "hɪr", uk: "hɪə" },
    "listen": { us: "ˈlɪsən", uk: "ˈlɪsən" },
    "whisper": { us: "ˈwɪspər", uk: "ˈwɪspə" },
    "shout": { us: "ʃaʊt", uk: "ʃaʊt" },
    "scream": { us: "skriːm", uk: "skriːm" },
    "yell": { us: "jel", uk: "jel" },
    "roar": { us: "rɔːr", uk: "rɔː" },
    "bark": { us: "bɑːrk", uk: "bɑːk" },
    "meow": { us: "miˈaʊ", uk: "miˈaʊ" },
    "moo": { us: "muː", uk: "muː" },
    "neigh": { us: "neɪ", uk: "neɪ" },
    "chirp": { us: "tʃɜːrp", uk: "tʃɜːp" },
    "tweet": { us: "twiːt", uk: "twiːt" },
    "buzz": { us: "bʌz", uk: "bʌz" },
    "hum": { us: "hʌm", uk: "hʌm" },
    "ring": { us: "rɪŋ", uk: "rɪŋ" },
    "bell": { us: "bel", uk: "bel" },
    "alarm": { us: "əˈlɑːrm", uk: "əˈlɑːm" },
    "clock": { us: "klɑːk", uk: "klɒk" },
    "watch": { us: "wɑːtʃ", uk: "wɒtʃ" },
    "timer": { us: "ˈtaɪmər", uk: "ˈtaɪmə" },
    "schedule": { us: "ˈskedʒuːl", uk: "ˈʃedjuːl" },
    "appointment": { us: "əˈpɔɪntmənt", uk: "əˈpɔɪntmənt" },
    "meeting": { us: "ˈmiːtɪŋ", uk: "ˈmiːtɪŋ" },
    "conference": { us: "ˈkɑːnfərəns", uk: "ˈkɒnfərəns" },
    "interview": { us: "ˈɪntərvjuː", uk: "ˈɪntəvjuː" },
    "conversation": { us: "ˌkɑːnvərˈseɪʃən", uk: "ˌkɒnvəˈseɪʃən" },
    "discussion": { us: "dɪˈskʌʃən", uk: "dɪˈskʌʃən" },
    "chat": { us: "tʃæt", uk: "tʃæt" },
    "gossip": { us: "ˈɡɑːsɪp", uk: "ˈɡɒsɪp" },
    "rumor": { us: "ˈruːmər", uk: "ˈruːmə" },
    "news": { us: "nuːz", uk: "njuːz" },
    "information": { us: "ˌɪnfərˈmeɪʃən", uk: "ˌɪnfəˈmeɪʃən" },
    "data": { us: "ˈdeɪtə", uk: "ˈdeɪtə" },
    "fact": { us: "fækt", uk: "fækt" },
    "truth": { us: "truːθ", uk: "truːθ" },
    "lie": { us: "laɪ", uk: "laɪ" },
    "story": { us: "ˈstɔːri", uk: "ˈstɔːri" },
    "tale": { us: "teɪl", uk: "teɪl" },
    "legend": { us: "ˈledʒənd", uk: "ˈledʒənd" },
    "myth": { us: "mɪθ", uk: "mɪθ" },
    "history": { us: "ˈhɪstəri", uk: "ˈhɪstəri" },
    "past": { us: "pæst", uk: "pɑːst" },
    "present": { us: "ˈprezənt", uk: "ˈprezənt" },
    "future": { us: "ˈfjuːtʃər", uk: "ˈfjuːtʃə" },
    "memory": { us: "ˈmeməri", uk: "ˈmeməri" },
    "dream": { us: "driːm", uk: "driːm" },
    "nightmare": { us: "ˈnaɪtmer", uk: "ˈnaɪtmeə" },
    "hope": { us: "hoʊp", uk: "həʊp" },
    "wish": { us: "wɪʃ", uk: "wɪʃ" },
    "desire": { us: "dɪˈzaɪər", uk: "dɪˈzaɪə" },
    "goal": { us: "ɡoʊl", uk: "ɡəʊl" },
    "target": { us: "ˈtɑːrɡət", uk: "ˈtɑːɡət" },
    "aim": { us: "eɪm", uk: "eɪm" },
    "purpose": { us: "ˈpɜːrpəs", uk: "ˈpɜːpəs" },
    "reason": { us: "ˈriːzən", uk: "ˈriːzən" },
    "cause": { us: "kɔːz", uk: "kɔːz" },
    "effect": { us: "ɪˈfekt", uk: "ɪˈfekt" },
    "result": { us: "rɪˈzʌlt", uk: "rɪˈzʌlt" },
    "consequence": { us: "ˈkɑːnsəkwəns", uk: "ˈkɒnsəkwəns" },
    "outcome": { us: "ˈaʊtkʌm", uk: "ˈaʊtkʌm" },
    "solution": { us: "səˈluːʃən", uk: "səˈluːʃən" },
    "answer": { us: "ˈænsər", uk: "ˈɑːnsə" },
    "question": { us: "ˈkwestʃən", uk: "ˈkwestʃən" },
    "problem": { us: "ˈprɑːbləm", uk: "ˈprɒbləm" },
    "issue": { us: "ˈɪʃuː", uk: "ˈɪʃuː" },
    "trouble": { us: "ˈtrʌbəl", uk: "ˈtrʌbəl" },
    "difficulty": { us: "ˈdɪfɪkəlti", uk: "ˈdɪfɪkəlti" },
    "challenge": { us: "ˈtʃælɪndʒ", uk: "ˈtʃælɪndʒ" },
    "obstacle": { us: "ˈɑːbstəkəl", uk: "ˈɒbstəkəl" },
    "barrier": { us: "ˈbæriər", uk: "ˈbæriə" },
    "wall": { us: "wɔːl", uk: "wɔːl" },
    "fence": { us: "fens", uk: "fens" },
    "gate": { us: "ɡeɪt", uk: "ɡeɪt" },
    "door": { us: "dɔːr", uk: "dɔː" },
    "window": { us: "ˈwɪndoʊ", uk: "ˈwɪndəʊ" },
    "roof": { us: "ruːf", uk: "ruːf" },
    "floor": { us: "flɔːr", uk: "flɔː" },
    "ceiling": { us: "ˈsiːlɪŋ", uk: "ˈsiːlɪŋ" },
    "room": { us: "ruːm", uk: "ruːm" },
    "house": { us: "haʊs", uk: "haʊs" },
    "home": { us: "hoʊm", uk: "həʊm" },
    "building": { us: "ˈbɪldɪŋ", uk: "ˈbɪldɪŋ" },
    "office": { us: "ˈɔːfɪs", uk: "ˈɒfɪs" },
    "school": { us: "skuːl", uk: "skuːl" },
    "hospital": { us: "ˈhɑːspɪtəl", uk: "ˈhɒspɪtəl" },
    "store": { us: "stɔːr", uk: "stɔː" },
    "shop": { us: "ʃɑːp", uk: "ʃɒp" },
    "market": { us: "ˈmɑːrkət", uk: "ˈmɑːkət" },
    "restaurant": { us: "ˈrestərɑːnt", uk: "ˈrestərɒnt" },
    "hotel": { us: "hoʊˈtel", uk: "həʊˈtel" },
    "bank": { us: "bæŋk", uk: "bæŋk" },
    "library": { us: "ˈlaɪbreri", uk: "ˈlaɪbrəri" },
    "museum": { us: "mjuˈziːəm", uk: "mjuˈziːəm" },
    "theater": { us: "ˈθiːətər", uk: "ˈθɪətə" },
    "cinema": { us: "ˈsɪnəmə", uk: "ˈsɪnəmə" },
    "park": { us: "pɑːrk", uk: "pɑːk" },
    "garden": { us: "ˈɡɑːrdən", uk: "ˈɡɑːdən" },
    "beach": { us: "biːtʃ", uk: "biːtʃ" },
    "mountain": { us: "ˈmaʊntən", uk: "ˈmaʊntən" },
    "river": { us: "ˈrɪvər", uk: "ˈrɪvə" },
    "lake": { us: "leɪk", uk: "leɪk" },
    "ocean": { us: "ˈoʊʃən", uk: "ˈəʊʃən" },
    "sea": { us: "siː", uk: "siː" },
    "island": { us: "ˈaɪlənd", uk: "ˈaɪlənd" },
    "forest": { us: "ˈfɔːrəst", uk: "ˈfɒrəst" },
    "tree": { us: "triː", uk: "triː" },
    "flower": { us: "ˈflaʊər", uk: "ˈflaʊə" },
    "grass": { us: "ɡræs", uk: "ɡrɑːs" },
    "leaf": { us: "liːf", uk: "liːf" },
    "branch": { us: "bræntʃ", uk: "brɑːntʃ" },
    "root": { us: "ruːt", uk: "ruːt" },
    "seed": { us: "siːd", uk: "siːd" },
    "plant": { us: "plænt", uk: "plɑːnt" },
    "animal": { us: "ˈænɪməl", uk: "ˈænɪməl" },
    "bird": { us: "bɜːrd", uk: "bɜːd" },
    "fish": { us: "fɪʃ", uk: "fɪʃ" },
    "dog": { us: "dɔːɡ", uk: "dɒɡ" },
    "cat": { us: "kæt", uk: "kæt" },
    "horse": { us: "hɔːrs", uk: "hɔːs" },
    "cow": { us: "kaʊ", uk: "kaʊ" },
    "pig": { us: "pɪɡ", uk: "pɪɡ" },
    "sheep": { us: "ʃiːp", uk: "ʃiːp" },
    "chicken": { us: "ˈtʃɪkən", uk: "ˈtʃɪkən" },
    "duck": { us: "dʌk", uk: "dʌk" },
    "goose": { us: "ɡuːs", uk: "ɡuːs" },
    "turkey": { us: "ˈtɜːrki", uk: "ˈtɜːki" },
    "rabbit": { us: "ˈræbət", uk: "ˈræbət" },
    "mouse": { us: "maʊs", uk: "maʊs" },
    "rat": { us: "ræt", uk: "ræt" },
    "elephant": { us: "ˈeləfənt", uk: "ˈeləfənt" },
    "lion": { us: "ˈlaɪən", uk: "ˈlaɪən" },
    "tiger": { us: "ˈtaɪɡər", uk: "ˈtaɪɡə" },
    "bear": { us: "ber", uk: "beə" },
    "wolf": { us: "wʊlf", uk: "wʊlf" },
    "fox": { us: "fɑːks", uk: "fɒks" },
    "deer": { us: "dɪr", uk: "dɪə" },
    "monkey": { us: "ˈmʌŋki", uk: "ˈmʌŋki" },
    "snake": { us: "sneɪk", uk: "sneɪk" },
    "frog": { us: "frɔːɡ", uk: "frɒɡ" },
    "butterfly": { us: "ˈbʌtərflaɪ", uk: "ˈbʌtəflaɪ" },
    "bee": { us: "biː", uk: "biː" },
    "ant": { us: "ænt", uk: "ænt" },
    "spider": { us: "ˈspaɪdər", uk: "ˈspaɪdə" },
    
    // 身体部位
    "body": { us: "ˈbɑːdi", uk: "ˈbɒdi" },
    "head": { us: "hed", uk: "hed" },
    "face": { us: "feɪs", uk: "feɪs" },
    "eye": { us: "aɪ", uk: "aɪ" },
    "nose": { us: "noʊz", uk: "nəʊz" },
    "mouth": { us: "maʊθ", uk: "maʊθ" },
    "ear": { us: "ɪr", uk: "ɪə" },
    "hair": { us: "her", uk: "heə" },
    "neck": { us: "nek", uk: "nek" },
    "shoulder": { us: "ˈʃoʊldər", uk: "ˈʃəʊldə" },
    "arm": { us: "ɑːrm", uk: "ɑːm" },
    "hand": { us: "hænd", uk: "hænd" },
    "finger": { us: "ˈfɪŋɡər", uk: "ˈfɪŋɡə" },
    "thumb": { us: "θʌm", uk: "θʌm" },
    "chest": { us: "tʃest", uk: "tʃest" },
    "back": { us: "bæk", uk: "bæk" },
    "stomach": { us: "ˈstʌmək", uk: "ˈstʌmək" },
    "leg": { us: "leɡ", uk: "leɡ" },
    "foot": { us: "fʊt", uk: "fʊt" },
    "toe": { us: "toʊ", uk: "təʊ" },
    "knee": { us: "niː", uk: "niː" },
    "heart": { us: "hɑːrt", uk: "hɑːt" },
    "brain": { us: "breɪn", uk: "breɪn" },
    "tooth": { us: "tuːθ", uk: "tuːθ" },
    "teeth": { us: "tiːθ", uk: "tiːθ" },
    "tongue": { us: "tʌŋ", uk: "tʌŋ" },
    "lip": { us: "lɪp", uk: "lɪp" },
    "skin": { us: "skɪn", uk: "skɪn" },
    "bone": { us: "boʊn", uk: "bəʊn" },
    "blood": { us: "blʌd", uk: "blʌd" },
    
    // 衣物
    "clothes": { us: "kloʊðz", uk: "kləʊðz" },
    "shirt": { us: "ʃɜːrt", uk: "ʃɜːt" },
    "pants": { us: "pænts", uk: "pænts" },
    "dress": { us: "dres", uk: "dres" },
    "skirt": { us: "skɜːrt", uk: "skɜːt" },
    "jacket": { us: "ˈdʒækət", uk: "ˈdʒækət" },
    "coat": { us: "koʊt", uk: "kəʊt" },
    "hat": { us: "hæt", uk: "hæt" },
    "cap": { us: "kæp", uk: "kæp" },
    "shoes": { us: "ʃuːz", uk: "ʃuːz" },
    "socks": { us: "sɑːks", uk: "sɒks" },
    "gloves": { us: "ɡlʌvz", uk: "ɡlʌvz" },
    "belt": { us: "belt", uk: "belt" },
    "tie": { us: "taɪ", uk: "taɪ" },
    "scarf": { us: "skɑːrf", uk: "skɑːf" },
    "glasses": { us: "ˈɡlæsəz", uk: "ˈɡlɑːsəz" },
    "watch": { us: "wɑːtʃ", uk: "wɒtʃ" },
    "ring": { us: "rɪŋ", uk: "rɪŋ" },
    "necklace": { us: "ˈnekləs", uk: "ˈnekləs" },
    "earring": { us: "ˈɪrɪŋ", uk: "ˈɪərɪŋ" },
    "bracelet": { us: "ˈbreɪslət", uk: "ˈbreɪslət" },
    
    // 交通工具
    "car": { us: "kɑːr", uk: "kɑː" },
    "bus": { us: "bʌs", uk: "bʌs" },
    "train": { us: "treɪn", uk: "treɪn" },
    "plane": { us: "pleɪn", uk: "pleɪn" },
    "ship": { us: "ʃɪp", uk: "ʃɪp" },
    "boat": { us: "boʊt", uk: "bəʊt" },
    "bicycle": { us: "ˈbaɪsəkəl", uk: "ˈbaɪsəkəl" },
    "motorcycle": { us: "ˈmoʊtərsaɪkəl", uk: "ˈməʊtəsaɪkəl" },
    "truck": { us: "trʌk", uk: "trʌk" },
    "taxi": { us: "ˈtæksi", uk: "ˈtæksi" },
    "subway": { us: "ˈsʌbweɪ", uk: "ˈsʌbweɪ" },
    "helicopter": { us: "ˈhelɪkɑːptər", uk: "ˈhelɪkɒptə" },
    "rocket": { us: "ˈrɑːkət", uk: "ˈrɒkət" },
    
    // 天气
    "weather": { us: "ˈweðər", uk: "ˈweðə" },
    "sun": { us: "sʌn", uk: "sʌn" },
    "moon": { us: "muːn", uk: "muːn" },
    "star": { us: "stɑːr", uk: "stɑː" },
    "cloud": { us: "klaʊd", uk: "klaʊd" },
    "rain": { us: "reɪn", uk: "reɪn" },
    "snow": { us: "snoʊ", uk: "snəʊ" },
    "wind": { us: "wɪnd", uk: "wɪnd" },
    "storm": { us: "stɔːrm", uk: "stɔːm" },
    "thunder": { us: "ˈθʌndər", uk: "ˈθʌndə" },
    "lightning": { us: "ˈlaɪtnɪŋ", uk: "ˈlaɪtnɪŋ" },
    "hot": { us: "hɑːt", uk: "hɒt" },
    "cold": { us: "koʊld", uk: "kəʊld" },
    "warm": { us: "wɔːrm", uk: "wɔːm" },
    "cool": { us: "kuːl", uk: "kuːl" },
    "dry": { us: "draɪ", uk: "draɪ" },
    "wet": { us: "wet", uk: "wet" },
    "sunny": { us: "ˈsʌni", uk: "ˈsʌni" },
    "cloudy": { us: "ˈklaʊdi", uk: "ˈklaʊdi" },
    "rainy": { us: "ˈreɪni", uk: "ˈreɪni" },
    "snowy": { us: "ˈsnoʊi", uk: "ˈsnəʊi" },
    "windy": { us: "ˈwɪndi", uk: "ˈwɪndi" },
    "foggy": { us: "ˈfɔːɡi", uk: "ˈfɒɡi" },
    "icy": { us: "ˈaɪsi", uk: "ˈaɪsi" },
    "temperature": { us: "ˈtemprətʃər", uk: "ˈtemprətʃə" },
    "degree": { us: "dɪˈɡriː", uk: "dɪˈɡriː" },
    "celsius": { us: "ˈselsiəs", uk: "ˈselsiəs" },
    "fahrenheit": { us: "ˈfærənhaɪt", uk: "ˈfærənhaɪt" }
};

// 字典版本信息
const DICT_VERSION = "1.0.0";
const DICT_LAST_UPDATED = "2024-01-15";

// 字典统计信息
const DICT_STATS = {
    totalWords: Object.keys(defaultDict).length,
    categories: [
        "基础词汇", "数字", "颜色", "家庭", "时间", "食物", "动作",
        "身体部位", "衣物", "交通工具", "天气", "动物", "自然"
    ],
    accents: ["us", "uk"]
};

// 导出字典和相关信息
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        defaultDict,
        DICT_VERSION,
        DICT_LAST_UPDATED,
        DICT_STATS
    };
} else if (typeof window !== 'undefined') {
    window.PhoneticsData = {
        defaultDict,
        DICT_VERSION,
        DICT_LAST_UPDATED,
        DICT_STATS
    };
}

// 工厂函数
function createPhoneticsData() {
    return {
        defaultDict: JSON.parse(JSON.stringify(defaultDict)),
        version: DICT_VERSION,
        lastUpdated: DICT_LAST_UPDATED,
        stats: JSON.parse(JSON.stringify(DICT_STATS))
    };
}

if (typeof window !== 'undefined') {
    window.createPhoneticsData = createPhoneticsData;
}