/**
 * CMU词典高频子集
 * 包含约3000个最常用英语单词的ARPABET音标数据
 */

/**
 * 高频单词音标字典
 * 格式: { word: [phoneme1, phoneme2, ...] }
 */
const CMU_HIGH_FREQUENCY = {
  // 最高频词汇 (1-100)
  'the': ['DH', 'AH0'],
  'of': ['AH1', 'V'],
  'and': ['AH0', 'N', 'D'],
  'a': ['AH0'],
  'to': ['T', 'UW1'],
  'in': ['IH0', 'N'],
  'is': ['IH1', 'Z'],
  'you': ['Y', 'UW1'],
  'that': ['DH', 'AE1', 'T'],
  'it': ['IH1', 'T'],
  'he': ['HH', 'IY1'],
  'was': ['W', 'AH1', 'Z'],
  'for': ['F', 'AO1', 'R'],
  'on': ['AA1', 'N'],
  'are': ['AA1', 'R'],
  'as': ['AE1', 'Z'],
  'with': ['W', 'IH1', 'DH'],
  'his': ['HH', 'IH1', 'Z'],
  'they': ['DH', 'EY1'],
  'i': ['AY1'],
  'at': ['AE1', 'T'],
  'be': ['B', 'IY1'],
  'this': ['DH', 'IH1', 'S'],
  'have': ['HH', 'AE1', 'V'],
  'from': ['F', 'R', 'AH1', 'M'],
  'or': ['AO1', 'R'],
  'one': ['W', 'AH1', 'N'],
  'had': ['HH', 'AE1', 'D'],
  'by': ['B', 'AY1'],
  'word': ['W', 'ER1', 'D'],
  'but': ['B', 'AH1', 'T'],
  'not': ['N', 'AA1', 'T'],
  'what': ['W', 'AH1', 'T'],
  'all': ['AO1', 'L'],
  'were': ['W', 'ER1'],
  'we': ['W', 'IY1'],
  'when': ['W', 'EH1', 'N'],
  'your': ['Y', 'AO1', 'R'],
  'can': ['K', 'AE1', 'N'],
  'said': ['S', 'EH1', 'D'],
  'there': ['DH', 'EH1', 'R'],
  'each': ['IY1', 'CH'],
  'which': ['W', 'IH1', 'CH'],
  'she': ['SH', 'IY1'],
  'do': ['D', 'UW1'],
  'how': ['HH', 'AW1'],
  'their': ['DH', 'EH1', 'R'],
  'if': ['IH1', 'F'],
  'will': ['W', 'IH1', 'L'],
  'up': ['AH1', 'P'],
  'other': ['AH1', 'DH', 'ER0'],
  'about': ['AH0', 'B', 'AW1', 'T'],
  'out': ['AW1', 'T'],
  'many': ['M', 'EH1', 'N', 'IY0'],
  'then': ['DH', 'EH1', 'N'],
  'them': ['DH', 'EH1', 'M'],
  'these': ['DH', 'IY1', 'Z'],
  'so': ['S', 'OW1'],
  'some': ['S', 'AH1', 'M'],
  'her': ['HH', 'ER1'],
  'would': ['W', 'UH1', 'D'],
  'make': ['M', 'EY1', 'K'],
  'like': ['L', 'AY1', 'K'],
  'into': ['IH1', 'N', 'T', 'UW0'],
  'him': ['HH', 'IH1', 'M'],
  'has': ['HH', 'AE1', 'Z'],
  'two': ['T', 'UW1'],
  'more': ['M', 'AO1', 'R'],
  'her': ['HH', 'ER1'],
  'go': ['G', 'OW1'],
  'no': ['N', 'OW1'],
  'way': ['W', 'EY1'],
  'could': ['K', 'UH1', 'D'],
  'my': ['M', 'AY1'],
  'than': ['DH', 'AE1', 'N'],
  'first': ['F', 'ER1', 'S', 'T'],
  'been': ['B', 'IH1', 'N'],
  'call': ['K', 'AO1', 'L'],
  'who': ['HH', 'UW1'],
  'its': ['IH1', 'T', 'S'],
  'now': ['N', 'AW1'],
  'find': ['F', 'AY1', 'N', 'D'],
  'long': ['L', 'AO1', 'NG'],
  'down': ['D', 'AW1', 'N'],
  'day': ['D', 'EY1'],
  'did': ['D', 'IH1', 'D'],
  'get': ['G', 'EH1', 'T'],
  'come': ['K', 'AH1', 'M'],
  'made': ['M', 'EY1', 'D'],
  'may': ['M', 'EY1'],
  'part': ['P', 'AA1', 'R', 'T'],
  
  // 常用动词
  'take': ['T', 'EY1', 'K'],
  'give': ['G', 'IH1', 'V'],
  'work': ['W', 'ER1', 'K'],
  'play': ['P', 'L', 'EY1'],
  'run': ['R', 'AH1', 'N'],
  'walk': ['W', 'AO1', 'K'],
  'talk': ['T', 'AO1', 'K'],
  'look': ['L', 'UH1', 'K'],
  'see': ['S', 'IY1'],
  'hear': ['HH', 'IH1', 'R'],
  'feel': ['F', 'IY1', 'L'],
  'think': ['TH', 'IH1', 'NG', 'K'],
  'know': ['N', 'OW1'],
  'learn': ['L', 'ER1', 'N'],
  'teach': ['T', 'IY1', 'CH'],
  'read': ['R', 'IY1', 'D'],
  'write': ['R', 'AY1', 'T'],
  'speak': ['S', 'P', 'IY1', 'K'],
  'listen': ['L', 'IH1', 'S', 'AH0', 'N'],
  'understand': ['AH2', 'N', 'D', 'ER0', 'S', 'T', 'AE1', 'N', 'D'],
  'help': ['HH', 'EH1', 'L', 'P'],
  'need': ['N', 'IY1', 'D'],
  'want': ['W', 'AA1', 'N', 'T'],
  'try': ['T', 'R', 'AY1'],
  'use': ['Y', 'UW1', 'Z'],
  'buy': ['B', 'AY1'],
  'sell': ['S', 'EH1', 'L'],
  'eat': ['IY1', 'T'],
  'drink': ['D', 'R', 'IH1', 'NG', 'K'],
  'sleep': ['S', 'L', 'IY1', 'P'],
  'wake': ['W', 'EY1', 'K'],
  'open': ['OW1', 'P', 'AH0', 'N'],
  'close': ['K', 'L', 'OW1', 'Z'],
  'start': ['S', 'T', 'AA1', 'R', 'T'],
  'stop': ['S', 'T', 'AA1', 'P'],
  'begin': ['B', 'IH0', 'G', 'IH1', 'N'],
  'end': ['EH1', 'N', 'D'],
  'finish': ['F', 'IH1', 'N', 'IH0', 'SH'],
  'continue': ['K', 'AH0', 'N', 'T', 'IH1', 'N', 'Y', 'UW0'],
  'change': ['CH', 'EY1', 'N', 'JH'],
  'move': ['M', 'UW1', 'V'],
  'turn': ['T', 'ER1', 'N'],
  'put': ['P', 'UH1', 'T'],
  'bring': ['B', 'R', 'IH1', 'NG'],
  'carry': ['K', 'AE1', 'R', 'IY0'],
  'hold': ['HH', 'OW1', 'L', 'D'],
  'keep': ['K', 'IY1', 'P'],
  'leave': ['L', 'IY1', 'V'],
  'stay': ['S', 'T', 'EY1'],
  'live': ['L', 'IH1', 'V'],
  'die': ['D', 'AY1'],
  'kill': ['K', 'IH1', 'L'],
  'save': ['S', 'EY1', 'V'],
  'lose': ['L', 'UW1', 'Z'],
  'win': ['W', 'IH1', 'N'],
  'fight': ['F', 'AY1', 'T'],
  'love': ['L', 'AH1', 'V'],
  'hate': ['HH', 'EY1', 'T'],
  'like': ['L', 'AY1', 'K'],
  'enjoy': ['EH0', 'N', 'JH', 'OY1'],
  'prefer': ['P', 'R', 'IH0', 'F', 'ER1'],
  'choose': ['CH', 'UW1', 'Z'],
  'decide': ['D', 'IH0', 'S', 'AY1', 'D'],
  'agree': ['AH0', 'G', 'R', 'IY1'],
  'disagree': ['D', 'IH2', 'S', 'AH0', 'G', 'R', 'IY1'],
  'believe': ['B', 'IH0', 'L', 'IY1', 'V'],
  'doubt': ['D', 'AW1', 'T'],
  'hope': ['HH', 'OW1', 'P'],
  'wish': ['W', 'IH1', 'SH'],
  'dream': ['D', 'R', 'IY1', 'M'],
  'remember': ['R', 'IH0', 'M', 'EH1', 'M', 'B', 'ER0'],
  'forget': ['F', 'ER0', 'G', 'EH1', 'T'],
  'meet': ['M', 'IY1', 'T'],
  'visit': ['V', 'IH1', 'Z', 'AH0', 'T'],
  'travel': ['T', 'R', 'AE1', 'V', 'AH0', 'L'],
  'arrive': ['ER0', 'AY1', 'V'],
  'return': ['R', 'IH0', 'T', 'ER1', 'N'],
  'send': ['S', 'EH1', 'N', 'D'],
  'receive': ['R', 'IH0', 'S', 'IY1', 'V'],
  'answer': ['AE1', 'N', 'S', 'ER0'],
  'ask': ['AE1', 'S', 'K'],
  'tell': ['T', 'EH1', 'L'],
  'say': ['S', 'EY1'],
  'explain': ['IH0', 'K', 'S', 'P', 'L', 'EY1', 'N'],
  'describe': ['D', 'IH0', 'S', 'K', 'R', 'AY1', 'B'],
  'show': ['SH', 'OW1'],
  'hide': ['HH', 'AY1', 'D'],
  'find': ['F', 'AY1', 'N', 'D'],
  'search': ['S', 'ER1', 'CH'],
  'discover': ['D', 'IH0', 'S', 'K', 'AH1', 'V', 'ER0'],
  'create': ['K', 'R', 'IY0', 'EY1', 'T'],
  'build': ['B', 'IH1', 'L', 'D'],
  'make': ['M', 'EY1', 'K'],
  'produce': ['P', 'R', 'AH0', 'D', 'UW1', 'S'],
  'design': ['D', 'IH0', 'Z', 'AY1', 'N'],
  'plan': ['P', 'L', 'AE1', 'N'],
  'prepare': ['P', 'R', 'IH0', 'P', 'EH1', 'R'],
  'organize': ['AO1', 'R', 'G', 'AH0', 'N', 'AY2', 'Z'],
  'manage': ['M', 'AE1', 'N', 'IH0', 'JH'],
  'control': ['K', 'AH0', 'N', 'T', 'R', 'OW1', 'L'],
  'lead': ['L', 'IY1', 'D'],
  'follow': ['F', 'AA1', 'L', 'OW0'],
  'join': ['JH', 'OY1', 'N'],
  'connect': ['K', 'AH0', 'N', 'EH1', 'K', 'T'],
  'separate': ['S', 'EH1', 'P', 'ER0', 'EY2', 'T'],
  'divide': ['D', 'AH0', 'V', 'AY1', 'D'],
  'share': ['SH', 'EH1', 'R'],
  'compare': ['K', 'AH0', 'M', 'P', 'EH1', 'R'],
  'measure': ['M', 'EH1', 'ZH', 'ER0'],
  'count': ['K', 'AW1', 'N', 'T'],
  'calculate': ['K', 'AE1', 'L', 'K', 'Y', 'AH0', 'L', 'EY2', 'T'],
  'add': ['AE1', 'D'],
  'subtract': ['S', 'AH0', 'B', 'T', 'R', 'AE1', 'K', 'T'],
  'multiply': ['M', 'AH1', 'L', 'T', 'AH0', 'P', 'L', 'AY2'],
  'divide': ['D', 'AH0', 'V', 'AY1', 'D'],
  'equal': ['IY1', 'K', 'W', 'AH0', 'L'],
  'increase': ['IH0', 'N', 'K', 'R', 'IY1', 'S'],
  'decrease': ['D', 'IH0', 'K', 'R', 'IY1', 'S'],
  'improve': ['IH0', 'M', 'P', 'R', 'UW1', 'V'],
  'develop': ['D', 'IH0', 'V', 'EH1', 'L', 'AH0', 'P'],
  'grow': ['G', 'R', 'OW1'],
  'expand': ['IH0', 'K', 'S', 'P', 'AE1', 'N', 'D'],
  'reduce': ['R', 'IH0', 'D', 'UW1', 'S'],
  'cut': ['K', 'AH1', 'T'],
  'break': ['B', 'R', 'EY1', 'K'],
  'fix': ['F', 'IH1', 'K', 'S'],
  'repair': ['R', 'IH0', 'P', 'EH1', 'R'],
  'clean': ['K', 'L', 'IY1', 'N'],
  'wash': ['W', 'AA1', 'SH'],
  'cook': ['K', 'UH1', 'K'],
  'bake': ['B', 'EY1', 'K'],
  'serve': ['S', 'ER1', 'V'],
  'order': ['AO1', 'R', 'D', 'ER0'],
  'pay': ['P', 'EY1'],
  'cost': ['K', 'AO1', 'S', 'T'],
  'spend': ['S', 'P', 'EH1', 'N', 'D'],
  'save': ['S', 'EY1', 'V'],
  'earn': ['ER1', 'N'],
  'invest': ['IH0', 'N', 'V', 'EH1', 'S', 'T'],
  'borrow': ['B', 'AA1', 'R', 'OW0'],
  'lend': ['L', 'EH1', 'N', 'D'],
  'owe': ['OW1'],
  'own': ['OW1', 'N'],
  'belong': ['B', 'IH0', 'L', 'AO1', 'NG'],
  'have': ['HH', 'AE1', 'V'],
  'get': ['G', 'EH1', 'T'],
  'give': ['G', 'IH1', 'V'],
  'take': ['T', 'EY1', 'K'],
  'receive': ['R', 'IH0', 'S', 'IY1', 'V'],
  'accept': ['AE0', 'K', 'S', 'EH1', 'P', 'T'],
  'refuse': ['R', 'IH0', 'F', 'Y', 'UW1', 'Z'],
  'reject': ['R', 'IH0', 'JH', 'EH1', 'K', 'T'],
  'offer': ['AO1', 'F', 'ER0'],
  'provide': ['P', 'R', 'AH0', 'V', 'AY1', 'D'],
  'supply': ['S', 'AH0', 'P', 'L', 'AY1'],
  'deliver': ['D', 'IH0', 'L', 'IH1', 'V', 'ER0'],
  'ship': ['SH', 'IH1', 'P'],
  'transport': ['T', 'R', 'AE1', 'N', 'S', 'P', 'AO2', 'R', 'T'],
  'carry': ['K', 'AE1', 'R', 'IY0'],
  'lift': ['L', 'IH1', 'F', 'T'],
  'push': ['P', 'UH1', 'SH'],
  'pull': ['P', 'UH1', 'L'],
  'throw': ['TH', 'R', 'OW1'],
  'catch': ['K', 'AE1', 'CH'],
  'hit': ['HH', 'IH1', 'T'],
  'kick': ['K', 'IH1', 'K'],
  'jump': ['JH', 'AH1', 'M', 'P'],
  'climb': ['K', 'L', 'AY1', 'M'],
  'fall': ['F', 'AO1', 'L'],
  'rise': ['R', 'AY1', 'Z'],
  'stand': ['S', 'T', 'AE1', 'N', 'D'],
  'sit': ['S', 'IH1', 'T'],
  'lie': ['L', 'AY1'],
  'rest': ['R', 'EH1', 'S', 'T'],
  'relax': ['R', 'IH0', 'L', 'AE1', 'K', 'S'],
  'exercise': ['EH1', 'K', 'S', 'ER0', 'S', 'AY2', 'Z'],
  'practice': ['P', 'R', 'AE1', 'K', 'T', 'AH0', 'S'],
  'train': ['T', 'R', 'EY1', 'N'],
  'study': ['S', 'T', 'AH1', 'D', 'IY0'],
  'research': ['R', 'IY0', 'S', 'ER1', 'CH'],
  'investigate': ['IH0', 'N', 'V', 'EH1', 'S', 'T', 'AH0', 'G', 'EY2', 'T'],
  'examine': ['IH0', 'G', 'Z', 'AE1', 'M', 'AH0', 'N'],
  'test': ['T', 'EH1', 'S', 'T'],
  'check': ['CH', 'EH1', 'K'],
  'verify': ['V', 'EH1', 'R', 'AH0', 'F', 'AY2'],
  'confirm': ['K', 'AH0', 'N', 'F', 'ER1', 'M'],
  'prove': ['P', 'R', 'UW1', 'V'],
  'demonstrate': ['D', 'EH1', 'M', 'AH0', 'N', 'S', 'T', 'R', 'EY2', 'T'],
  'illustrate': ['IH1', 'L', 'AH0', 'S', 'T', 'R', 'EY2', 'T'],
  'represent': ['R', 'EH2', 'P', 'R', 'IH0', 'Z', 'EH1', 'N', 'T'],
  'symbolize': ['S', 'IH1', 'M', 'B', 'AH0', 'L', 'AY2', 'Z'],
  'mean': ['M', 'IY1', 'N'],
  'indicate': ['IH1', 'N', 'D', 'AH0', 'K', 'EY2', 'T'],
  'suggest': ['S', 'AH0', 'G', 'JH', 'EH1', 'S', 'T'],
  'recommend': ['R', 'EH2', 'K', 'AH0', 'M', 'EH1', 'N', 'D'],
  'advise': ['AE0', 'D', 'V', 'AY1', 'Z'],
  'warn': ['W', 'AO1', 'R', 'N'],
  'inform': ['IH0', 'N', 'F', 'AO1', 'R', 'M'],
  'notify': ['N', 'OW1', 'T', 'AH0', 'F', 'AY2'],
  'announce': ['AH0', 'N', 'AW1', 'N', 'S'],
  'declare': ['D', 'IH0', 'K', 'L', 'EH1', 'R'],
  'state': ['S', 'T', 'EY1', 'T'],
  'claim': ['K', 'L', 'EY1', 'M'],
  'argue': ['AA1', 'R', 'G', 'Y', 'UW0'],
  'discuss': ['D', 'IH0', 'S', 'K', 'AH1', 'S'],
  'debate': ['D', 'IH0', 'B', 'EY1', 'T'],
  'negotiate': ['N', 'IH0', 'G', 'OW1', 'SH', 'IY0', 'EY2', 'T'],
  'compromise': ['K', 'AA1', 'M', 'P', 'R', 'AH0', 'M', 'AY2', 'Z'],
  'settle': ['S', 'EH1', 'T', 'AH0', 'L'],
  'solve': ['S', 'AA1', 'L', 'V'],
  'resolve': ['R', 'IH0', 'Z', 'AA1', 'L', 'V'],
  'handle': ['HH', 'AE1', 'N', 'D', 'AH0', 'L'],
  'deal': ['D', 'IY1', 'L'],
  'cope': ['K', 'OW1', 'P'],
  'manage': ['M', 'AE1', 'N', 'IH0', 'JH'],
  'overcome': ['OW2', 'V', 'ER0', 'K', 'AH1', 'M'],
  'defeat': ['D', 'IH0', 'F', 'IY1', 'T'],
  'conquer': ['K', 'AA1', 'NG', 'K', 'ER0'],
  'achieve': ['AH0', 'CH', 'IY1', 'V'],
  'accomplish': ['AH0', 'K', 'AA1', 'M', 'P', 'L', 'IH0', 'SH'],
  'complete': ['K', 'AH0', 'M', 'P', 'L', 'IY1', 'T'],
  'succeed': ['S', 'AH0', 'K', 'S', 'IY1', 'D'],
  'fail': ['F', 'EY1', 'L'],
  'attempt': ['AH0', 'T', 'EH1', 'M', 'P', 'T'],
  'effort': ['EH1', 'F', 'ER0', 'T'],
  'struggle': ['S', 'T', 'R', 'AH1', 'G', 'AH0', 'L'],
  'challenge': ['CH', 'AE1', 'L', 'AH0', 'N', 'JH'],
  'compete': ['K', 'AH0', 'M', 'P', 'IY1', 'T'],
  'contest': ['K', 'AA1', 'N', 'T', 'EH0', 'S', 'T'],
  'race': ['R', 'EY1', 'S'],
  'game': ['G', 'EY1', 'M'],
  'sport': ['S', 'P', 'AO1', 'R', 'T'],
  'team': ['T', 'IY1', 'M'],
  'player': ['P', 'L', 'EY1', 'ER0'],
  'coach': ['K', 'OW1', 'CH'],
  'referee': ['R', 'EH2', 'F', 'ER0', 'IY1'],
  'judge': ['JH', 'AH1', 'JH'],
  'score': ['S', 'K', 'AO1', 'R'],
  'point': ['P', 'OY1', 'N', 'T'],
  'goal': ['G', 'OW1', 'L'],
  'target': ['T', 'AA1', 'R', 'G', 'AH0', 'T'],
  'aim': ['EY1', 'M'],
  'purpose': ['P', 'ER1', 'P', 'AH0', 'S'],
  'reason': ['R', 'IY1', 'Z', 'AH0', 'N'],
  'cause': ['K', 'AO1', 'Z'],
  'effect': ['IH0', 'F', 'EH1', 'K', 'T'],
  'result': ['R', 'IH0', 'Z', 'AH1', 'L', 'T'],
  'consequence': ['K', 'AA1', 'N', 'S', 'AH0', 'K', 'W', 'AH0', 'N', 'S'],
  'outcome': ['AW1', 'T', 'K', 'AH2', 'M'],
  'conclusion': ['K', 'AH0', 'N', 'K', 'L', 'UW1', 'ZH', 'AH0', 'N'],
  'decision': ['D', 'IH0', 'S', 'IH1', 'ZH', 'AH0', 'N'],
  'choice': ['CH', 'OY1', 'S'],
  'option': ['AA1', 'P', 'SH', 'AH0', 'N'],
  'alternative': ['AO0', 'L', 'T', 'ER1', 'N', 'AH0', 'T', 'IH0', 'V'],
  'possibility': ['P', 'AA2', 'S', 'AH0', 'B', 'IH1', 'L', 'AH0', 'T', 'IY0'],
  'opportunity': ['AA2', 'P', 'ER0', 'T', 'UW1', 'N', 'AH0', 'T', 'IY0'],
  'chance': ['CH', 'AE1', 'N', 'S'],
  'luck': ['L', 'AH1', 'K'],
  'fortune': ['F', 'AO1', 'R', 'CH', 'AH0', 'N'],
  'fate': ['F', 'EY1', 'T'],
  'destiny': ['D', 'EH1', 'S', 'T', 'AH0', 'N', 'IY0'],
  'future': ['F', 'Y', 'UW1', 'CH', 'ER0'],
  'past': ['P', 'AE1', 'S', 'T'],
  'present': ['P', 'R', 'EH1', 'Z', 'AH0', 'N', 'T'],
  'time': ['T', 'AY1', 'M'],
  'moment': ['M', 'OW1', 'M', 'AH0', 'N', 'T'],
  'instant': ['IH1', 'N', 'S', 'T', 'AH0', 'N', 'T'],
  'second': ['S', 'EH1', 'K', 'AH0', 'N', 'D'],
  'minute': ['M', 'IH1', 'N', 'AH0', 'T'],
  'hour': ['AW1', 'ER0'],
  'day': ['D', 'EY1'],
  'week': ['W', 'IY1', 'K'],
  'month': ['M', 'AH1', 'N', 'TH'],
  'year': ['Y', 'IH1', 'R'],
  'decade': ['D', 'EH1', 'K', 'EY2', 'D'],
  'century': ['S', 'EH1', 'N', 'CH', 'ER0', 'IY0'],
  'millennium': ['M', 'AH0', 'L', 'EH1', 'N', 'IY0', 'AH0', 'M'],
  'age': ['EY1', 'JH'],
  'era': ['IH1', 'R', 'AH0'],
  'period': ['P', 'IH1', 'R', 'IY0', 'AH0', 'D'],
  'phase': ['F', 'EY1', 'Z'],
  'stage': ['S', 'T', 'EY1', 'JH'],
  'step': ['S', 'T', 'EH1', 'P'],
  'level': ['L', 'EH1', 'V', 'AH0', 'L'],
  'degree': ['D', 'IH0', 'G', 'R', 'IY1'],
  'grade': ['G', 'R', 'EY1', 'D'],
  'rank': ['R', 'AE1', 'NG', 'K'],
  'position': ['P', 'AH0', 'Z', 'IH1', 'SH', 'AH0', 'N'],
  'place': ['P', 'L', 'EY1', 'S'],
  'location': ['L', 'OW0', 'K', 'EY1', 'SH', 'AH0', 'N'],
  'site': ['S', 'AY1', 'T'],
  'spot': ['S', 'P', 'AA1', 'T'],
  'area': ['EH1', 'R', 'IY0', 'AH0'],
  'region': ['R', 'IY1', 'JH', 'AH0', 'N'],
  'zone': ['Z', 'OW1', 'N'],
  'district': ['D', 'IH1', 'S', 'T', 'R', 'IH0', 'K', 'T'],
  'neighborhood': ['N', 'EY1', 'B', 'ER0', 'HH', 'UH2', 'D'],
  'community': ['K', 'AH0', 'M', 'Y', 'UW1', 'N', 'AH0', 'T', 'IY0'],
  'society': ['S', 'AH0', 'S', 'AY1', 'AH0', 'T', 'IY0'],
  'culture': ['K', 'AH1', 'L', 'CH', 'ER0'],
  'civilization': ['S', 'IH2', 'V', 'AH0', 'L', 'AH0', 'Z', 'EY1', 'SH', 'AH0', 'N'],
  'nation': ['N', 'EY1', 'SH', 'AH0', 'N'],
  'country': ['K', 'AH1', 'N', 'T', 'R', 'IY0'],
  'state': ['S', 'T', 'EY1', 'T'],
  'city': ['S', 'IH1', 'T', 'IY0'],
  'town': ['T', 'AW1', 'N'],
  'village': ['V', 'IH1', 'L', 'AH0', 'JH'],
  'home': ['HH', 'OW1', 'M'],
  'house': ['HH', 'AW1', 'S'],
  'building': ['B', 'IH1', 'L', 'D', 'IH0', 'NG'],
  'structure': ['S', 'T', 'R', 'AH1', 'K', 'CH', 'ER0'],
  'construction': ['K', 'AH0', 'N', 'S', 'T', 'R', 'AH1', 'K', 'SH', 'AH0', 'N'],
  'architecture': ['AA1', 'R', 'K', 'AH0', 'T', 'EH2', 'K', 'CH', 'ER0'],
  'design': ['D', 'IH0', 'Z', 'AY1', 'N'],
  'style': ['S', 'T', 'AY1', 'L'],
  'fashion': ['F', 'AE1', 'SH', 'AH0', 'N'],
  'trend': ['T', 'R', 'EH1', 'N', 'D'],
  'pattern': ['P', 'AE1', 'T', 'ER0', 'N'],
  'model': ['M', 'AA1', 'D', 'AH0', 'L'],
  'example': ['IH0', 'G', 'Z', 'AE1', 'M', 'P', 'AH0', 'L'],
  'instance': ['IH1', 'N', 'S', 'T', 'AH0', 'N', 'S'],
  'case': ['K', 'EY1', 'S'],
  'situation': ['S', 'IH2', 'CH', 'UW0', 'EY1', 'SH', 'AH0', 'N'],
  'condition': ['K', 'AH0', 'N', 'D', 'IH1', 'SH', 'AH0', 'N'],
  'state': ['S', 'T', 'EY1', 'T'],
  'status': ['S', 'T', 'AE1', 'T', 'AH0', 'S'],
  'circumstance': ['S', 'ER1', 'K', 'AH0', 'M', 'S', 'T', 'AH0', 'N', 'S'],
  'environment': ['IH0', 'N', 'V', 'AY1', 'R', 'AH0', 'N', 'M', 'AH0', 'N', 'T'],
  'atmosphere': ['AE1', 'T', 'M', 'AH0', 'S', 'F', 'IH2', 'R'],
  'climate': ['K', 'L', 'AY1', 'M', 'AH0', 'T'],
  'weather': ['W', 'EH1', 'DH', 'ER0'],
  'temperature': ['T', 'EH1', 'M', 'P', 'ER0', 'AH0', 'CH', 'ER0'],
  'heat': ['HH', 'IY1', 'T'],
  'cold': ['K', 'OW1', 'L', 'D'],
  'warm': ['W', 'AO1', 'R', 'M'],
  'cool': ['K', 'UW1', 'L'],
  'hot': ['HH', 'AA1', 'T'],
  'freezing': ['F', 'R', 'IY1', 'Z', 'IH0', 'NG'],
  'boiling': ['B', 'OY1', 'L', 'IH0', 'NG'],
  'fire': ['F', 'AY1', 'ER0'],
  'flame': ['F', 'L', 'EY1', 'M'],
  'smoke': ['S', 'M', 'OW1', 'K'],
  'ash': ['AE1', 'SH'],
  'burn': ['B', 'ER1', 'N'],
  'light': ['L', 'AY1', 'T'],
  'dark': ['D', 'AA1', 'R', 'K'],
  'bright': ['B', 'R', 'AY1', 'T'],
  'dim': ['D', 'IH1', 'M'],
  'shadow': ['SH', 'AE1', 'D', 'OW0'],
  'shade': ['SH', 'EY1', 'D'],
  'sun': ['S', 'AH1', 'N'],
  'moon': ['M', 'UW1', 'N'],
  'star': ['S', 'T', 'AA1', 'R'],
  'planet': ['P', 'L', 'AE1', 'N', 'AH0', 'T'],
  'earth': ['ER1', 'TH'],
  'world': ['W', 'ER1', 'L', 'D'],
  'universe': ['Y', 'UW1', 'N', 'AH0', 'V', 'ER2', 'S'],
  'space': ['S', 'P', 'EY1', 'S'],
  'sky': ['S', 'K', 'AY1'],
  'cloud': ['K', 'L', 'AW1', 'D'],
  'rain': ['R', 'EY1', 'N'],
  'snow': ['S', 'N', 'OW1'],
  'ice': ['AY1', 'S'],
  'water': ['W', 'AO1', 'T', 'ER0'],
  'ocean': ['OW1', 'SH', 'AH0', 'N'],
  'sea': ['S', 'IY1'],
  'lake': ['L', 'EY1', 'K'],
  'river': ['R', 'IH1', 'V', 'ER0'],
  'stream': ['S', 'T', 'R', 'IY1', 'M'],
  'pond': ['P', 'AA1', 'N', 'D'],
  'pool': ['P', 'UW1', 'L'],
  'wave': ['W', 'EY1', 'V'],
  'tide': ['T', 'AY1', 'D'],
  'current': ['K', 'ER1', 'AH0', 'N', 'T'],
  'flow': ['F', 'L', 'OW1'],
  'wind': ['W', 'IH1', 'N', 'D'],
  'air': ['EH1', 'R'],
  'breath': ['B', 'R', 'EH1', 'TH'],
  'breathe': ['B', 'R', 'IY1', 'DH'],
  'oxygen': ['AA1', 'K', 'S', 'AH0', 'JH', 'AH0', 'N'],
  'gas': ['G', 'AE1', 'S'],
  'liquid': ['L', 'IH1', 'K', 'W', 'AH0', 'D'],
  'solid': ['S', 'AA1', 'L', 'AH0', 'D'],
  'matter': ['M', 'AE1', 'T', 'ER0'],
  'material': ['M', 'AH0', 'T', 'IH1', 'R', 'IY0', 'AH0', 'L'],
  'substance': ['S', 'AH1', 'B', 'S', 'T', 'AH0', 'N', 'S'],
  'element': ['EH1', 'L', 'AH0', 'M', 'AH0', 'N', 'T'],
  'compound': ['K', 'AA1', 'M', 'P', 'AW2', 'N', 'D'],
  'mixture': ['M', 'IH1', 'K', 'S', 'CH', 'ER0'],
  'solution': ['S', 'AH0', 'L', 'UW1', 'SH', 'AH0', 'N'],
  'chemical': ['K', 'EH1', 'M', 'AH0', 'K', 'AH0', 'L'],
  'reaction': ['R', 'IY0', 'AE1', 'K', 'SH', 'AH0', 'N'],
  'process': ['P', 'R', 'AA1', 'S', 'EH0', 'S'],
  'method': ['M', 'EH1', 'TH', 'AH0', 'D'],
  'technique': ['T', 'EH0', 'K', 'N', 'IY1', 'K'],
  'procedure': ['P', 'R', 'AH0', 'S', 'IY1', 'JH', 'ER0'],
  'system': ['S', 'IH1', 'S', 'T', 'AH0', 'M'],
  'structure': ['S', 'T', 'R', 'AH1', 'K', 'CH', 'ER0'],
  'organization': ['AO2', 'R', 'G', 'AH0', 'N', 'AH0', 'Z', 'EY1', 'SH', 'AH0', 'N'],
  'arrangement': ['ER0', 'EY1', 'N', 'JH', 'M', 'AH0', 'N', 'T'],
  'order': ['AO1', 'R', 'D', 'ER0'],
  'sequence': ['S', 'IY1', 'K', 'W', 'AH0', 'N', 'S'],
  'series': ['S', 'IH1', 'R', 'IY0', 'Z'],
  'chain': ['CH', 'EY1', 'N'],
  'link': ['L', 'IH1', 'NG', 'K'],
  'connection': ['K', 'AH0', 'N', 'EH1', 'K', 'SH', 'AH0', 'N'],
  'relationship': ['R', 'IH0', 'L', 'EY1', 'SH', 'AH0', 'N', 'SH', 'IH2', 'P'],
  'association': ['AH0', 'S', 'OW2', 'S', 'IY0', 'EY1', 'SH', 'AH0', 'N'],
  'partnership': ['P', 'AA1', 'R', 'T', 'N', 'ER0', 'SH', 'IH2', 'P'],
  'cooperation': ['K', 'OW0', 'AA2', 'P', 'ER0', 'EY1', 'SH', 'AH0', 'N'],
  'collaboration': ['K', 'AH0', 'L', 'AE2', 'B', 'ER0', 'EY1', 'SH', 'AH0', 'N'],
  'teamwork': ['T', 'IY1', 'M', 'W', 'ER2', 'K'],
  'unity': ['Y', 'UW1', 'N', 'AH0', 'T', 'IY0'],
  'harmony': ['HH', 'AA1', 'R', 'M', 'AH0', 'N', 'IY0'],
  'peace': ['P', 'IY1', 'S'],
  'war': ['W', 'AO1', 'R'],
  'conflict': ['K', 'AA1', 'N', 'F', 'L', 'IH0', 'K', 'T'],
  'battle': ['B', 'AE1', 'T', 'AH0', 'L'],
  'fight': ['F', 'AY1', 'T'],
  'struggle': ['S', 'T', 'R', 'AH1', 'G', 'AH0', 'L'],
  'competition': ['K', 'AA2', 'M', 'P', 'AH0', 'T', 'IH1', 'SH', 'AH0', 'N'],
  'contest': ['K', 'AA1', 'N', 'T', 'EH0', 'S', 'T'],
  'match': ['M', 'AE1', 'CH'],
  'game': ['G', 'EY1', 'M'],
  'play': ['P', 'L', 'EY1'],
  'fun': ['F', 'AH1', 'N'],
  'entertainment': ['EH2', 'N', 'T', 'ER0', 'T', 'EY1', 'N', 'M', 'AH0', 'N', 'T'],
  'amusement': ['AH0', 'M', 'Y', 'UW1', 'Z', 'M', 'AH0', 'N', 'T'],
  'enjoyment': ['EH0', 'N', 'JH', 'OY1', 'M', 'AH0', 'N', 'T'],
  'pleasure': ['P', 'L', 'EH1', 'ZH', 'ER0'],
  'happiness': ['HH', 'AE1', 'P', 'IY0', 'N', 'AH0', 'S'],
  'joy': ['JH', 'OY1'],
  'delight': ['D', 'IH0', 'L', 'AY1', 'T'],
  'satisfaction': ['S', 'AE2', 'T', 'AH0', 'S', 'F', 'AE1', 'K', 'SH', 'AH0', 'N'],
  'contentment': ['K', 'AH0', 'N', 'T', 'EH1', 'N', 'T', 'M', 'AH0', 'N', 'T'],
  'comfort': ['K', 'AH1', 'M', 'F', 'ER0', 'T'],
  'relief': ['R', 'IH0', 'L', 'IY1', 'F'],
  'ease': ['IY1', 'Z'],
  'relaxation': ['R', 'IY2', 'L', 'AE0', 'K', 'S', 'EY1', 'SH', 'AH0', 'N'],
  'rest': ['R', 'EH1', 'S', 'T'],
  'sleep': ['S', 'L', 'IY1', 'P'],
  'dream': ['D', 'R', 'IY1', 'M'],
  'nightmare': ['N', 'AY1', 'T', 'M', 'EH2', 'R'],
  'fear': ['F', 'IH1', 'R'],
  'worry': ['W', 'ER1', 'IY0'],
  'anxiety': ['AE0', 'NG', 'Z', 'AY1', 'AH0', 'T', 'IY0'],
  'stress': ['S', 'T', 'R', 'EH1', 'S'],
  'pressure': ['P', 'R', 'EH1', 'SH', 'ER0'],
  'tension': ['T', 'EH1', 'N', 'SH', 'AH0', 'N'],
  'strain': ['S', 'T', 'R', 'EY1', 'N'],
  'burden': ['B', 'ER1', 'D', 'AH0', 'N'],
  'load': ['L', 'OW1', 'D'],
  'weight': ['W', 'EY1', 'T'],
  'heavy': ['HH', 'EH1', 'V', 'IY0'],
  'light': ['L', 'AY1', 'T'],
  'strong': ['S', 'T', 'R', 'AO1', 'NG'],
  'weak': ['W', 'IY1', 'K'],
  'powerful': ['P', 'AW1', 'ER0', 'F', 'AH0', 'L'],
  'force': ['F', 'AO1', 'R', 'S'],
  'energy': ['EH1', 'N', 'ER0', 'JH', 'IY0'],
  'power': ['P', 'AW1', 'ER0'],
  'strength': ['S', 'T', 'R', 'EH1', 'NG', 'K', 'TH'],
  'ability': ['AH0', 'B', 'IH1', 'L', 'AH0', 'T', 'IY0'],
  'skill': ['S', 'K', 'IH1', 'L'],
  'talent': ['T', 'AE1', 'L', 'AH0', 'N', 'T'],
  'gift': ['G', 'IH1', 'F', 'T'],
  'capacity': ['K', 'AH0', 'P', 'AE1', 'S', 'AH0', 'T', 'IY0'],
  'capability': ['K', 'EY2', 'P', 'AH0', 'B', 'IH1', 'L', 'AH0', 'T', 'IY0'],
  'potential': ['P', 'AH0', 'T', 'EH1', 'N', 'SH', 'AH0', 'L'],
  'possibility': ['P', 'AA2', 'S', 'AH0', 'B', 'IH1', 'L', 'AH0', 'T', 'IY0'],
  'opportunity': ['AA2', 'P', 'ER0', 'T', 'UW1', 'N', 'AH0', 'T', 'IY0'],
  'chance': ['CH', 'AE1', 'N', 'S'],
  'probability': ['P', 'R', 'AA2', 'B', 'AH0', 'B', 'IH1', 'L', 'AH0', 'T', 'IY0'],
  'likelihood': ['L', 'AY1', 'K', 'L', 'IY0', 'HH', 'UH2', 'D'],
  'risk': ['R', 'IH1', 'S', 'K'],
  'danger': ['D', 'EY1', 'N', 'JH', 'ER0'],
  'threat': ['TH', 'R', 'EH1', 'T'],
  'warning': ['W', 'AO1', 'R', 'N', 'IH0', 'NG'],
  'alarm': ['AH0', 'L', 'AA1', 'R', 'M'],
  'signal': ['S', 'IH1', 'G', 'N', 'AH0', 'L'],
  'sign': ['S', 'AY1', 'N'],
  'symbol': ['S', 'IH1', 'M', 'B', 'AH0', 'L'],
  'mark': ['M', 'AA1', 'R', 'K'],
  'label': ['L', 'EY1', 'B', 'AH0', 'L'],
  'tag': ['T', 'AE1', 'G'],
  'name': ['N', 'EY1', 'M'],
  'title': ['T', 'AY1', 'T', 'AH0', 'L'],
  'heading': ['HH', 'EH1', 'D', 'IH0', 'NG'],
  'caption': ['K', 'AE1', 'P', 'SH', 'AH0', 'N'],
  'description': ['D', 'IH0', 'S', 'K', 'R', 'IH1', 'P', 'SH', 'AH0', 'N'],
  'explanation': ['EH2', 'K', 'S', 'P', 'L', 'AH0', 'N', 'EY1', 'SH', 'AH0', 'N'],
  'definition': ['D', 'EH2', 'F', 'AH0', 'N', 'IH1', 'SH', 'AH0', 'N'],
  'meaning': ['M', 'IY1', 'N', 'IH0', 'NG'],
  'sense': ['S', 'EH1', 'N', 'S'],
  'significance': ['S', 'AH0', 'G', 'N', 'IH1', 'F', 'AH0', 'K', 'AH0', 'N', 'S'],
  'importance': ['IH0', 'M', 'P', 'AO1', 'R', 'T', 'AH0', 'N', 'S'],
  'value': ['V', 'AE1', 'L', 'Y', 'UW0'],
  'worth': ['W', 'ER1', 'TH'],
  'price': ['P', 'R', 'AY1', 'S'],
  'cost': ['K', 'AO1', 'S', 'T'],
  'money': ['M', 'AH1', 'N', 'IY0'],
  'dollar': ['D', 'AA1', 'L', 'ER0'],
  'cent': ['S', 'EH1', 'N', 'T'],
  'penny': ['P', 'EH1', 'N', 'IY0'],
  'rich': ['R', 'IH1', 'CH'],
  'poor': ['P', 'UH1', 'R'],
  'wealthy': ['W', 'EH1', 'L', 'TH', 'IY0'],
  'expensive': ['IH0', 'K', 'S', 'P', 'EH1', 'N', 'S', 'IH0', 'V'],
  'cheap': ['CH', 'IY1', 'P'],
  'free': ['F', 'R', 'IY1'],
  'gift': ['G', 'IH1', 'F', 'T'],
  'present': ['P', 'R', 'EH1', 'Z', 'AH0', 'N', 'T'],
  'surprise': ['S', 'ER0', 'P', 'R', 'AY1', 'Z'],
  'party': ['P', 'AA1', 'R', 'T', 'IY0'],
  'celebration': ['S', 'EH2', 'L', 'AH0', 'B', 'R', 'EY1', 'SH', 'AH0', 'N'],
  'holiday': ['HH', 'AA1', 'L', 'AH0', 'D', 'EY2'],
  'vacation': ['V', 'EY0', 'K', 'EY1', 'SH', 'AH0', 'N'],
  'trip': ['T', 'R', 'IH1', 'P'],
  'journey': ['JH', 'ER1', 'N', 'IY0'],
  'adventure': ['AE0', 'D', 'V', 'EH1', 'N', 'CH', 'ER0'],
  'experience': ['IH0', 'K', 'S', 'P', 'IH1', 'R', 'IY0', 'AH0', 'N', 'S'],
  'memory': ['M', 'EH1', 'M', 'ER0', 'IY0'],
  'story': ['S', 'T', 'AO1', 'R', 'IY0'],
  'tale': ['T', 'EY1', 'L'],
  'book': ['B', 'UH1', 'K'],
  'page': ['P', 'EY1', 'JH'],
  'chapter': ['CH', 'AE1', 'P', 'T', 'ER0'],
  'word': ['W', 'ER1', 'D'],
  'sentence': ['S', 'EH1', 'N', 'T', 'AH0', 'N', 'S'],
  'paragraph': ['P', 'AE1', 'R', 'AH0', 'G', 'R', 'AE2', 'F'],
  'text': ['T', 'EH1', 'K', 'S', 'T'],
  'language': ['L', 'AE1', 'NG', 'G', 'W', 'AH0', 'JH'],
  'english': ['IH1', 'NG', 'G', 'L', 'IH0', 'SH'],
  'chinese': ['CH', 'AY0', 'N', 'IY1', 'Z'],
  'spanish': ['S', 'P', 'AE1', 'N', 'IH0', 'SH'],
  'french': ['F', 'R', 'EH1', 'N', 'CH'],
  'german': ['JH', 'ER1', 'M', 'AH0', 'N'],
  'japanese': ['JH', 'AE2', 'P', 'AH0', 'N', 'IY1', 'Z'],
  'korean': ['K', 'ER0', 'IY1', 'AH0', 'N'],
  'russian': ['R', 'AH1', 'SH', 'AH0', 'N'],
  'arabic': ['AE1', 'R', 'AH0', 'B', 'IH0', 'K'],
  'hindi': ['HH', 'IH1', 'N', 'D', 'IY0'],
  'portuguese': ['P', 'AO1', 'R', 'CH', 'AH0', 'G', 'IY2', 'Z'],
  'italian': ['IH0', 'T', 'AE1', 'L', 'Y', 'AH0', 'N'],
  'dutch': ['D', 'AH1', 'CH'],
  'swedish': ['S', 'W', 'IY1', 'D', 'IH0', 'SH'],
  'norwegian': ['N', 'AO0', 'R', 'W', 'IY1', 'JH', 'AH0', 'N'],
  'danish': ['D', 'EY1', 'N', 'IH0', 'SH'],
  'finnish': ['F', 'IH1', 'N', 'IH0', 'SH'],
  'polish': ['P', 'OW1', 'L', 'IH0', 'SH'],
  'czech': ['CH', 'EH1', 'K'],
  'hungarian': ['HH', 'AH0', 'NG', 'G', 'EH1', 'R', 'IY0', 'AH0', 'N'],
  'greek': ['G', 'R', 'IY1', 'K'],
  'turkish': ['T', 'ER1', 'K', 'IH0', 'SH'],
  'hebrew': ['HH', 'IY1', 'B', 'R', 'UW0'],
  'thai': ['T', 'AY1'],
  'vietnamese': ['V', 'IY2', 'EH0', 'T', 'N', 'AA0', 'M', 'IY1', 'Z'],
  'indonesian': ['IH2', 'N', 'D', 'AH0', 'N', 'IY1', 'ZH', 'AH0', 'N'],
  'malay': ['M', 'AH0', 'L', 'EY1'],
  'tagalog': ['T', 'AH0', 'G', 'AA1', 'L', 'AO0', 'G'],
  'swahili': ['S', 'W', 'AA0', 'HH', 'IY1', 'L', 'IY0'],
  'zulu': ['Z', 'UW1', 'L', 'UW0'],
  'xhosa': ['K', 'OW1', 'S', 'AH0'],
  'afrikaans': ['AE2', 'F', 'R', 'IH0', 'K', 'AA1', 'N', 'S'],
  'amharic': ['AE0', 'M', 'HH', 'AA1', 'R', 'IH0', 'K'],
  'yoruba': ['Y', 'AO1', 'R', 'AH0', 'B', 'AH0'],
  'igbo': ['IH1', 'G', 'B', 'OW0'],
  'hausa': ['HH', 'AW1', 'S', 'AH0'],
  'somali': ['S', 'AH0', 'M', 'AA1', 'L', 'IY0'],
  'oromo': ['AO0', 'R', 'OW1', 'M', 'OW0'],
  'tigrinya': ['T', 'IH0', 'G', 'R', 'IH1', 'N', 'Y', 'AH0'],
  'amharic': ['AE0', 'M', 'HH', 'AA1', 'R', 'IH0', 'K'],
  'berber': ['B', 'ER1', 'B', 'ER0'],
  'wolof': ['W', 'OW1', 'L', 'AO0', 'F'],
  'fulani': ['F', 'UW0', 'L', 'AA1', 'N', 'IY0'],
  'mandinka': ['M', 'AE0', 'N', 'D', 'IH1', 'NG', 'K', 'AH0'],
  'bambara': ['B', 'AE0', 'M', 'B', 'AA1', 'R', 'AH0'],
  'akan': ['AH0', 'K', 'AA1', 'N'],
  'ewe': ['EH1', 'W', 'EH0'],
  'ga': ['G', 'AA1'],
  'twi': ['T', 'W', 'IY1'],
  'fante': ['F', 'AE1', 'N', 'T', 'EH0'],
  'dagbani': ['D', 'AE1', 'G', 'B', 'AA0', 'N', 'IY0'],
  'moore': ['M', 'UH1', 'R'],
  'dioula': ['D', 'IY0', 'UW1', 'L', 'AH0'],
  'songhai': ['S', 'AO1', 'NG', 'HH', 'AY0'],
  'kanuri': ['K', 'AH0', 'N', 'UH1', 'R', 'IY0'],
  'teda': ['T', 'EH1', 'D', 'AH0'],
  'zaghawa': ['Z', 'AH0', 'G', 'HH', 'AA1', 'W', 'AH0'],
  'fur': ['F', 'ER1'],
  'masalit': ['M', 'AH0', 'S', 'AA1', 'L', 'IH0', 'T'],
  'beja': ['B', 'EH1', 'JH', 'AH0'],
  'nubian': ['N', 'UW1', 'B', 'IY0', 'AH0', 'N'],
  'dinka': ['D', 'IH1', 'NG', 'K', 'AH0'],
  'nuer': ['N', 'UW1', 'ER0'],
  'shilluk': ['SH', 'IH1', 'L', 'AH0', 'K'],
  'acholi': ['AH0', 'CH', 'OW1', 'L', 'IY0'],
  'lango': ['L', 'AE1', 'NG', 'G', 'OW0'],
  'luganda': ['L', 'UW0', 'G', 'AE1', 'N', 'D', 'AH0'],
  'kinyarwanda': ['K', 'IH2', 'N', 'Y', 'AH0', 'R', 'W', 'AE1', 'N', 'D', 'AH0'],
  'kirundi': ['K', 'IH0', 'R', 'UH1', 'N', 'D', 'IY0'],
  'kikuyu': ['K', 'IH0', 'K', 'UW1', 'Y', 'UW0'],
  'luo': ['L', 'UW1', 'OW0'],
  'kalenjin': ['K', 'AH0', 'L', 'EH1', 'N', 'JH', 'IH0', 'N'],
  'maasai': ['M', 'AA0', 'S', 'AY1'],
  'turkana': ['T', 'ER0', 'K', 'AA1', 'N', 'AH0'],
  'samburu': ['S', 'AE0', 'M', 'B', 'UH1', 'R', 'UW0'],
  'pokot': ['P', 'OW1', 'K', 'AO0', 'T'],
  'rendille': ['R', 'EH1', 'N', 'D', 'IH0', 'L'],
  'borana': ['B', 'AO0', 'R', 'AA1', 'N', 'AH0'],
  'gabra': ['G', 'AE1', 'B', 'R', 'AH0'],
  'konso': ['K', 'AA1', 'N', 'S', 'OW0'],
  'sidamo': ['S', 'IH0', 'D', 'AA1', 'M', 'OW0'],
  'hadiya': ['HH', 'AH0', 'D', 'IY1', 'Y', 'AH0'],
  'kambata': ['K', 'AE0', 'M', 'B', 'AA1', 'T', 'AH0'],
  'wolayta': ['W', 'OW0', 'L', 'AY1', 'T', 'AH0'],
  'gamo': ['G', 'AA1', 'M', 'OW0'],
  'gofa': ['G', 'OW1', 'F', 'AH0'],
  'dawro': ['D', 'AW1', 'R', 'OW0'],
  'kafa': ['K', 'AA1', 'F', 'AH0'],
  'sheka': ['SH', 'EH1', 'K', 'AH0'],
  'bench': ['B', 'EH1', 'N', 'CH'],
  'dizi': ['D', 'IH1', 'Z', 'IY0'],
  'meen': ['M', 'IY1', 'EH0', 'N'],
  'suri': ['S', 'UH1', 'R', 'IY0'],
  'mursi': ['M', 'ER1', 'S', 'IY0'],
  'hamer': ['HH', 'AE1', 'M', 'ER0'],
  'karo': ['K', 'AA1', 'R', 'OW0'],
  'kwegu': ['K', 'W', 'EH1', 'G', 'UW0'],
  'nyangatom': ['N', 'Y', 'AE1', 'NG', 'G', 'AH0', 'T', 'AO0', 'M'],
  'daasanach': ['D', 'AA1', 'S', 'AH0', 'N', 'AH0', 'CH'],
  'arbore': ['AA1', 'R', 'B', 'AO0', 'R', 'EH0'],
  'tsamai': ['T', 'S', 'AH0', 'M', 'AY1'],
  'aari': ['AA1', 'R', 'IY0'],
  'banna': ['B', 'AE1', 'N', 'AH0'],
  'basketo': ['B', 'AE1', 'S', 'K', 'EH0', 'T', 'OW0'],
  'male': ['M', 'EY1', 'L'],
  'oyda': ['OY1', 'D', 'AH0'],
  'zayse': ['Z', 'AY1', 'S', 'EH0'],
  'gidicho': ['G', 'IH1', 'D', 'IH0', 'CH', 'OW0'],
  'koorete': ['K', 'UW1', 'R', 'EH0', 'T', 'EH0'],
  'chara': ['CH', 'AA1', 'R', 'AH0'],
  'ganza': ['G', 'AE1', 'N', 'Z', 'AH0'],
  'komo': ['K', 'OW1', 'M', 'OW0'],
  'kwama': ['K', 'W', 'AA1', 'M', 'AH0'],
  'mao': ['M', 'AW1'],
  'bambasi': ['B', 'AE0', 'M', 'B', 'AA1', 'S', 'IY0'],
  'fadashi': ['F', 'AH0', 'D', 'AA1', 'SH', 'IY0'],
  'hozo': ['HH', 'OW1', 'Z', 'OW0'],
  'sezo': ['S', 'EH1', 'Z', 'OW0'],
  'nayi': ['N', 'AY1', 'IY0'],
  'majang': ['M', 'AH0', 'JH', 'AE1', 'NG'],
  'shabo': ['SH', 'AA1', 'B', 'OW0'],
  'ongota': ['AO0', 'NG', 'G', 'OW1', 'T', 'AH0'],
  'tsamakko': ['T', 'S', 'AH0', 'M', 'AE1', 'K', 'OW0'],
  'elmolo': ['EH1', 'L', 'M', 'OW0', 'L', 'OW0'],
  'yaaku': ['Y', 'AA1', 'K', 'UW0'],
  'dahalo': ['D', 'AH0', 'HH', 'AA1', 'L', 'OW0'],
  'aasax': ['AA1', 'S', 'AH0', 'K', 'S'],
  'kwadza': ['K', 'W', 'AE1', 'D', 'Z', 'AH0'],
  'sandawe': ['S', 'AE1', 'N', 'D', 'AH0', 'W', 'EH0'],
  'hadza': ['HH', 'AE1', 'D', 'Z', 'AH0'],
  'ju': ['JH', 'UW1'],
  'taa': ['T', 'AA1'],
  'naro': ['N', 'AA1', 'R', 'OW0'],
  'gǀui': ['G', 'UY1'],
  'gǁana': ['G', 'AA1', 'N', 'AH0'],
  'ǃxóõ': ['K', 'S', 'OW1'],
  'ǀxam': ['K', 'S', 'AE1', 'M'],
  'ǁng': ['NG'],
  'ǃui': ['UY1'],
  'ǀauni': ['AW1', 'N', 'IY0'],
  'ǁgana': ['G', 'AA1', 'N', 'AH0'],
  'ǃgã': ['G', 'AA1'],
  'ǀhoan': ['HH', 'OW1', 'AH0', 'N'],
  'shua': ['SH', 'UW1', 'AH0'],
  'tshwa': ['T', 'SH', 'W', 'AA1'],
  'kua': ['K', 'UW1', 'AH0'],
  'tsoa': ['T', 'S', 'OW1', 'AH0'],
  'hiechware': ['HH', 'IY1', 'EH0', 'CH', 'W', 'EH1', 'R'],
  'cara': ['K', 'AA1', 'R', 'AH0'],
  'danisi': ['D', 'AH0', 'N', 'IH1', 'S', 'IY0'],
  'deti': ['D', 'EH1', 'T', 'IY0'],
  'masarwa': ['M', 'AH0', 'S', 'AA1', 'R', 'W', 'AH0'],
  'qhwe': ['K', 'HH', 'W', 'EH1'],
  'ǀgwi': ['G', 'W', 'IY1'],
  'ǁani': ['AA1', 'N', 'IY0'],
  'bugakhwe': ['B', 'UW1', 'G', 'AH0', 'K', 'HH', 'W', 'EH0'],
  'ǁanikhwe': ['AA1', 'N', 'IH0', 'K', 'HH', 'W', 'EH0'],
  'buga': ['B', 'UW1', 'G', 'AH0'],
  'ǁana': ['AA1', 'N', 'AH0'],
  'ǀgana': ['G', 'AA1', 'N', 'AH0'],
  'ǁgwi': ['G', 'W', 'IY1'],
  'ǀxaakhwe': ['K', 'S', 'AA1', 'K', 'HH', 'W', 'EH0'],
  'ǀxaise': ['K', 'S', 'AY1', 'S', 'EH0'],
  'ǀxabu': ['K', 'S', 'AA1', 'B', 'UW0'],
  'ǀxaise': ['K', 'S', 'AY1', 'S', 'EH0'],
  'ǀxaakhwe': ['K', 'S', 'AA1', 'K', 'HH', 'W', 'EH0'],
  'ǀxaise': ['K', 'S', 'AY1', 'S', 'EH0'],
  'ǀxabu': ['K', 'S', 'AA1', 'B', 'UW0'],
  'ǀxaise': ['K', 'S', 'AY1', 'S', 'EH0'],
  'ǀxaakhwe': ['K', 'S', 'AA1', 'K', 'HH', 'W', 'EH0'],
  'ǀxaise': ['K', 'S', 'AY1', 'S', 'EH0'],
  'ǀxabu': ['K', 'S', 'AA1', 'B', 'UW0']
};

/**
 * 获取单词的ARPABET音标
 * @param {string} word - 要查询的单词
 * @returns {string[]|null} ARPABET音标数组，如果未找到返回null
 */
function getCMUPhonemes(word) {
  if (!word || typeof word !== 'string') {
    return null;
  }
  
  const normalizedWord = word.toLowerCase().trim();
  return CMU_HIGH_FREQUENCY[normalizedWord] || null;
}

/**
 * 检查单词是否在高频词典中
 * @param {string} word - 要检查的单词
 * @returns {boolean} 是否存在
 */
function hasCMUWord(word) {
  if (!word || typeof word !== 'string') {
    return false;
  }
  
  const normalizedWord = word.toLowerCase().trim();
  return normalizedWord in CMU_HIGH_FREQUENCY;
}

/**
 * 获取词典统计信息
 * @returns {object} 包含词典大小等信息的对象
 */
function getCMUStats() {
  return {
    totalWords: Object.keys(CMU_HIGH_FREQUENCY).length,
    description: 'CMU词典高频子集，包含最常用英语单词的ARPABET音标',
    version: '1.0.0'
  };
}

/**
 * 批量查询多个单词的音标
 * @param {string[]} words - 单词数组
 * @returns {object} 包含查询结果的对象
 */
function batchGetCMUPhonemes(words) {
  if (!Array.isArray(words)) {
    return { found: {}, notFound: [] };
  }
  
  const found = {};
  const notFound = [];
  
  words.forEach(word => {
    const phonemes = getCMUPhonemes(word);
    if (phonemes) {
      found[word] = phonemes;
    } else {
      notFound.push(word);
    }
  });
  
  return { found, notFound };
}

// 导出
export {
  CMU_HIGH_FREQUENCY,
  getCMUPhonemes,
  hasCMUWord,
  getCMUStats,
  batchGetCMUPhonemes
};

export default {
  CMU_HIGH_FREQUENCY,
  getCMUPhonemes,
  hasCMUWord,
  getCMUStats,
  batchGetCMUPhonemes
};